//! Compile utilities once into a stylesheet. The renderer never re-interprets class strings.
use super::order_table;
use super::{TailwindClassError, validate_catalog_class};
use std::{borrow::Cow, cmp::Ordering, collections::BTreeMap, sync::Arc};
use takumi_core::style::{StyleSheet, ToCss};

#[derive(Clone, Debug, serde::Deserialize)]
struct PropertyOrder {
    order: Vec<u16>,
    count: usize,
}

#[derive(Clone)]
pub(crate) struct Utility {
    candidate: String,
    declarations: String,
    order: PropertyOrder,
    inline_display: Option<bool>,
}

/// Property/value pairs a lowering produces before CSS serialization.
type Css = Vec<(String, String)>;

/// Conflict key of an authored property/value list.
fn pair_order(pairs: &Css) -> PropertyOrder {
    let mut order = Vec::with_capacity(pairs.len());
    let mut count = 0;
    for (property, value) in pairs {
        let writes = composition_writes(property, value);
        // A property the table does not carry (an arbitrary shorthand such as `[border:...]`)
        // contributes no key: it sorts by declaration count and then the candidate name, which is
        // deterministic and is what the golden corpus pins.
        if let Some(index) = order_index(property) {
            order.extend(std::iter::repeat_n(index, writes));
        }
        // Every authored declaration counts, including the private slots: a utility that composes
        // more slots is the more specific one and sorts first, which is what makes an axis
        // override a whole-scale value.
        count += writes;
    }
    PropertyOrder { order, count }
}

/// Composition slots without the `--tw-` prefix, in both priority banks.
fn composition_slot(property: &str) -> Option<&str> {
    property
        .strip_prefix("--tw-important-")
        .or_else(|| property.strip_prefix("--tw-"))
}

/// How many declarations one authored pair stands for.
///
/// A value that fills a composed slot performs every write upstream needs for it, including the
/// geometry write this lowering inlines into the value (`order_table::COMPOSED_SLOTS`); a reset
/// only empties the composed slot. The conflict key needs the difference because a reset has to
/// land after the value it clears, no matter how the class string is ordered.
fn composition_writes(property: &str, value: &str) -> usize {
    let composes =
        composition_slot(property).is_some_and(|slot| order_table::COMPOSED_SLOTS.contains(&slot));
    if composes && !value.trim().is_empty() {
        2
    } else {
        1
    }
}

/// Order index of one authored property, mapping a private composition slot onto the public
/// property it feeds.
fn order_index(property: &str) -> Option<u16> {
    let Some(slot) = composition_slot(property) else {
        return order_table::index(property);
    };
    let base = if slot.starts_with("translate") {
        "translate"
    } else if slot.starts_with("scale") {
        "scale"
    } else if slot.starts_with("rotate") {
        "rotate"
    } else if slot.starts_with("shadow") {
        "box-shadow"
    } else if slot.starts_with("backdrop") {
        "backdrop-filter"
    } else {
        "filter"
    };
    order_table::index(base)
}

/// Conflict key of a generated declaration list: the property sequence plus how many
/// declarations the utility authored.
///
/// Catalog statics (`items-center`, `overflow-hidden`, `truncate`, …) are emitted as `@apply`,
/// whose declarations the stylesheet parser expands after this module is done. Their key is
/// therefore empty and they sort last: single-property statics still resolve by name exactly as
/// they do upstream, multi-property ones do not. The authoring reference records that boundary.
fn declaration_order(css: &str) -> PropertyOrder {
    let properties = declaration_properties(css);
    PropertyOrder {
        order: properties
            .iter()
            .map(|property| order_table::index(property).unwrap_or(u16::MAX))
            .collect(),
        count: properties.len(),
    }
}

/// Property names of a declaration list, in order. The input is generated by this module, so the
/// scan only has to handle the shapes it emits: `property:value;` pairs, values with nested
/// functions, and quoted strings.
fn declaration_properties(css: &str) -> Vec<String> {
    let mut properties = Vec::new();
    let mut start = 0;
    let mut depth = 0usize;
    let mut quote: Option<char> = None;
    let mut escaped = false;
    let push = |declaration: &str, properties: &mut Vec<String>| {
        let declaration = declaration.trim();
        if declaration.is_empty() {
            return;
        }
        if let Some((property, _)) = declaration.split_once(':') {
            properties.push(property.trim().to_ascii_lowercase());
        }
    };
    for (offset, ch) in css.char_indices() {
        if escaped {
            escaped = false;
            continue;
        }
        match ch {
            '\\' => escaped = true,
            _ if quote.is_some() => {
                if quote == Some(ch) {
                    quote = None;
                }
            }
            '\'' | '"' => quote = Some(ch),
            '(' | '[' => depth += 1,
            ')' | ']' => depth = depth.saturating_sub(1),
            ';' if depth == 0 => {
                push(&css[start..offset], &mut properties);
                start = offset + 1;
            }
            _ => {}
        }
    }
    push(&css[start..], &mut properties);
    properties
}

/// The authored CSS property for arbitrary declarations and visual composition utilities.
/// Existing layout utilities retain their conservative static-layout cache policy.
pub(crate) fn explicit_property(candidate: &str) -> Option<&str> {
    let candidate = candidate.strip_suffix('!').unwrap_or(candidate);
    arbitrary_property_parts(candidate)
        .map(|(property, _)| property)
        .or_else(|| super::visual::property(candidate))
}

fn arbitrary_property_parts(candidate: &str) -> Option<(&str, &str)> {
    let (property, value) = candidate
        .strip_prefix('[')?
        .strip_suffix(']')?
        .split_once(':')?;
    if property.is_empty() || value.is_empty() {
        return None;
    }
    Some((property, value))
}

pub(super) fn default_theme(name: &str) -> Option<&'static str> {
    crate::style::tokens::defaults()
        .get(name)
        .map(String::as_str)
}

/// Replaced media remains atomic even when the author uses `inline`.
pub(crate) fn layout_class<'a>(kind: &crate::NodeKind, class: &'a str) -> Cow<'a, str> {
    if matches!(
        kind,
        crate::NodeKind::Image { .. } | crate::NodeKind::Video { .. }
    ) {
        if matches!(class, "inline" | "inline!") || explicit_property(class) == Some("display") {
            return Cow::Owned(format!("motion-media-{class}"));
        }
    }
    Cow::Borrowed(class)
}

/// Compile each unique candidate once. All nodes and finite choices share the same
/// ordered rules; full layout, bounds probes and cache reuse use this stylesheet.
pub(crate) fn prepare_stylesheet(
    artifact: &crate::SceneArtifact,
) -> Result<(Arc<StyleSheet>, Vec<Vec<String>>), String> {
    let mut candidates = BTreeMap::new();
    let mut classes = Vec::with_capacity(artifact.nodes.len());
    for node in artifact.nodes.iter() {
        let mut names = Vec::with_capacity(node.class_names.len());
        for class in node.class_names.iter() {
            let selector = layout_class(&node.kind, class).into_owned();
            if candidates.contains_key(&selector) {
                names.push(selector);
                continue;
            }
            let mut utility = utility(class).map_err(|error| error.message(class))?;
            if matches!(
                node.kind,
                crate::NodeKind::Image { .. } | crate::NodeKind::Video { .. }
            ) && let Some(important) = utility.inline_display
            {
                utility.declarations =
                    css_declarations(&[("display".into(), "inline-block".into())], important)
                        .expect("atomic inline display");
            }
            names.push(selector.clone());
            candidates.entry(selector).or_insert(utility);
        }
        classes.push(names);
    }
    let mut utilities: Vec<_> = candidates
        .into_iter()
        .map(|(selector, utility)| (utility, selector))
        .collect();
    utilities.sort_by(|a, b| compare_utilities(&a.0, &b.0));
    let mut source = String::new();
    for (utility, selector) in utilities {
        source.push('.');
        cssparser::serialize_identifier(&selector, &mut source).expect("String writer");
        source.push('{');
        source.push_str(&utility.declarations);
        source.push_str("}\n");
    }
    StyleSheet::parse(&source)
        .map(|sheet| (Arc::new(sheet), classes))
        .map_err(|error| error.to_string())
}

pub(super) type ValueResolver<'a> = dyn Fn(&str, &str) -> Result<String, TailwindClassError> + 'a;

fn unresolved(property: &str, value: &str) -> Result<String, TailwindClassError> {
    if crate::style::contains_variable(value) {
        // Built-in tokens still resolve from the frozen table; anything else was an author
        // variable and is a boundary now.
        return crate::style::tokens::resolve(property, value)
            .map_err(|_| TailwindClassError::NeedsVariables);
    }
    if matches!(property, "font-family" | "font") {
        return crate::style::tokens::resolve(property, value).map_err(TailwindClassError::Css);
    }
    Ok(value.into())
}

pub(super) fn utility(candidate: &str) -> Result<Utility, TailwindClassError> {
    utility_with_values(candidate, &|property, raw| {
        if crate::style::contains_variable(raw) || matches!(property, "font-family" | "font") {
            crate::style::tokens::resolve(property, raw).map_err(TailwindClassError::Css)
        } else {
            Ok(raw.into())
        }
    })
}

pub(super) fn utility_with_theme(candidate: &str) -> Result<Utility, TailwindClassError> {
    utility_with_values(candidate, &unresolved)
}

pub(crate) fn utility_with_values(
    candidate: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Utility, TailwindClassError> {
    // A top-level colon is a variant prefix. Responsive and state variants are a permanent
    // boundary now that the canvas is fixed by the entry file's composition, so the check runs
    // before anything else and the message explains the replacement.
    let base = reject_variants(candidate)?;
    reject_variable_shorthand(base)?;
    let mut utility = match token_utility(&base, resolve)? {
        Some(utility) => utility,
        None => base_utility(&base, resolve)?,
    };
    utility.candidate = candidate.into();
    Ok(utility)
}

/// Utilities whose value comes from the frozen token table. There is no author theme any more, so
/// every named token is a built-in one.
fn token_utility(
    candidate: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Option<Utility>, TailwindClassError> {
    let has = |name: &str| default_theme(name).is_some();
    let important = candidate.ends_with('!');
    let class = candidate.strip_suffix('!').unwrap_or(candidate);
    let css = |values: Css| -> Result<Option<Utility>, TailwindClassError> {
        let order = pair_order(&values);
        let declarations = if class.trim_start_matches('-').starts_with("leading-")
            || class.trim_start_matches('-').starts_with("tracking-")
            || class.starts_with("font-") && values.iter().any(|(p, _)| p == "font-weight")
        {
            typography_declarations(&values, important, true)?
        } else {
            css_declarations(&values, important)?
        };
        Ok(Some(Utility {
            candidate: candidate.into(),
            order,
            declarations,
            inline_display: None,
        }))
    };
    let reference = |name: &str| {
        let mut ident = String::new();
        cssparser::serialize_identifier(name, &mut ident).expect("String writer");
        format!("var({ident})")
    };
    // A named text scale owns its companion typography; an explicit /leading modifier
    // replaces only line-height. Keep the original candidate for property ordering.
    if let Some(text) = class
        .strip_prefix("text-")
        .filter(|v| !v.starts_with("shadow-"))
    {
        let (size, leading) =
            modifier_at(text).map_or((text, None), |at| (&text[..at], Some(&text[at + 1..])));
        let name = format!("--text-{size}");
        if has(&name) && !has(&format!("--color-{size}")) {
            let mut values = vec![("font-size".into(), resolve("font-size", &reference(&name))?)];
            if let Some(leading) = leading {
                let leading_name = format!("--leading-{leading}");
                let value = if has(&leading_name) {
                    reference(&leading_name)
                } else if super::non_negative_number(leading) {
                    format!("calc({} * {leading})", reference("--spacing"))
                } else if let Some(raw) =
                    leading.strip_prefix('[').and_then(|v| v.strip_suffix(']'))
                {
                    decode_arbitrary(raw)?
                } else {
                    return Err(TailwindClassError::Unsupported);
                };
                values.push(("line-height".into(), resolve("line-height", &value)?));
            } else {
                for (suffix, property) in [
                    ("line-height", "line-height"),
                    ("letter-spacing", "letter-spacing"),
                    ("font-weight", "font-weight"),
                ] {
                    let companion = format!("{name}--{suffix}");
                    if has(&companion) {
                        values.push((property.into(), resolve(property, &reference(&companion))?));
                    }
                }
            }
            // Dynamic companion declarations have the same official property sort as their
            // explicit CSS; the base scale's two-property sample is adjusted below.
            let mut utility = css(values.clone())?.expect("CSS utility");
            let mut order = pair_order(&values);
            order.order.sort_unstable();
            order.order.dedup();
            utility.order = order;
            if leading.is_none() {
                utility.declarations = typography_declarations(&values, important, false)?;
            }
            return Ok(Some(utility));
        }
        // Arbitrary font sizes still use the fixed spacing scale for numeric leading.
        if let Some(leading) = leading {
            let raw = size
                .strip_prefix('[')
                .and_then(|s| s.strip_suffix(']'))
                .and_then(|raw| decode_arbitrary(raw).ok());
            if raw.as_deref().is_some_and(|value| {
                value.starts_with("length:")
                    || length_math(value)
                    || (!crate::style::contains_variable(value)
                        && crate::style::parse_property("font-size", value).is_ok()
                        && crate::style::parse_property("color", value).is_err())
            }) {
                let leading_name = format!("--leading-{leading}");
                let value = if has(&leading_name) {
                    Some(reference(&leading_name))
                } else if super::non_negative_number(leading) {
                    Some(format!("calc({} * {leading})", reference("--spacing")))
                } else {
                    None
                };
                if let Some(value) = value {
                    return base_utility(
                        &format!(
                            "text-{size}/[{}]{}",
                            value.replace(' ', "_"),
                            if important { "!" } else { "" }
                        ),
                        resolve,
                    )
                    .map(Some);
                }
            }
        }
    }
    // Ordinary tokens inherit the computed root value; inline tokens insert their raw
    // value into the utility and resolve references in the consuming node's scope.
    for (prefix, namespace, property) in [
        ("font-", "font", "font-family"),
        ("font-", "font-weight", "font-weight"),
        ("tracking-", "tracking", "letter-spacing"),
        ("leading-", "leading", "line-height"),
        ("aspect-", "aspect", "aspect-ratio"),
        ("rounded-tl-", "radius", "border-top-left-radius"),
        ("rounded-tr-", "radius", "border-top-right-radius"),
        ("rounded-bl-", "radius", "border-bottom-left-radius"),
        ("rounded-br-", "radius", "border-bottom-right-radius"),
        ("rounded-", "radius", "border-radius"),
    ] {
        if let Some(token) = class.strip_prefix(prefix) {
            let name = format!("--{namespace}-{token}");
            if has(&name) {
                return css(vec![(
                    property.into(),
                    resolve(property, &reference(&name))?,
                )]);
            }
        }
    }
    for (prefix, properties) in [
        (
            "rounded-t-",
            ["border-top-left-radius", "border-top-right-radius"],
        ),
        (
            "rounded-r-",
            ["border-top-right-radius", "border-bottom-right-radius"],
        ),
        (
            "rounded-b-",
            ["border-bottom-right-radius", "border-bottom-left-radius"],
        ),
        (
            "rounded-l-",
            ["border-top-left-radius", "border-bottom-left-radius"],
        ),
    ] {
        if let Some(token) = class.strip_prefix(prefix) {
            let name = format!("--radius-{token}");
            if has(&name) {
                return css(properties
                    .into_iter()
                    .map(|property| Ok((property.into(), resolve(property, &reference(&name))?)))
                    .collect::<Result<_, TailwindClassError>>()?);
            }
        }
    }
    for (prefix, namespace) in [
        ("backdrop-blur", "blur"),
        ("blur", "blur"),
        ("drop-shadow", "drop-shadow"),
    ] {
        if let Some(token) = class.strip_prefix(prefix).and_then(|v| v.strip_prefix('-')) {
            let name = format!("--{namespace}-{token}");
            if has(&name) {
                return base_utility(
                    &format!(
                        "{prefix}-[{}]{}",
                        reference(&name).replace(' ', "_"),
                        if important { "!" } else { "" }
                    ),
                    resolve,
                )
                .map(Some);
            }
        }
    }
    for prefix in [
        "max-w", "min-w", "max-h", "min-h", "basis", "size", "w", "h",
    ] {
        if let Some(token) = class.strip_prefix(prefix).and_then(|v| v.strip_prefix('-')) {
            let name = format!("--container-{token}");
            if has(&name) && !has(&format!("--spacing-{token}")) {
                return base_utility(
                    &format!(
                        "{prefix}-[{}]{}",
                        reference(&name).replace(' ', "_"),
                        if important { "!" } else { "" }
                    ),
                    resolve,
                )
                .map(Some);
            }
        }
    }
    let (unsigned, negative) = class
        .strip_prefix('-')
        .map_or((class, false), |v| (v, true));
    if negative && let Some(token) = unsigned.strip_prefix("tracking-") {
        let name = format!("--tracking-{token}");
        if has(&name) {
            return css(vec![(
                "letter-spacing".into(),
                resolve(
                    "letter-spacing",
                    &format!("calc({} * -1)", reference(&name)),
                )?,
            )]);
        }
    }
    for prefix in [
        "translate-x",
        "translate-y",
        "translate",
        "min-w",
        "max-w",
        "min-h",
        "max-h",
        "inset-x",
        "inset-y",
        "inset",
        "gap-x",
        "gap-y",
        "gap",
        "basis",
        "size",
        "leading",
        "w",
        "h",
        "px",
        "py",
        "pt",
        "pr",
        "pb",
        "pl",
        "ps",
        "pe",
        "p",
        "mx",
        "my",
        "mt",
        "mr",
        "mb",
        "ml",
        "ms",
        "me",
        "m",
        "top",
        "right",
        "bottom",
        "left",
    ] {
        let Some(token) = unsigned
            .strip_prefix(prefix)
            .and_then(|v| v.strip_prefix('-'))
        else {
            continue;
        };
        let name = format!("--spacing-{token}");
        let value = if prefix != "leading" && has(&name) {
            Some(reference(&name))
        } else if has("--spacing") && super::non_negative_number(token) {
            Some(format!("calc({} * {token})", reference("--spacing")))
        } else {
            None
        };
        if let Some(value) = value {
            // Reuse the existing negative-value, axis and visual composition lowering.
            let lowered = format!(
                "{}{prefix}-[{}]{}",
                if negative { "-" } else { "" },
                value.replace(' ', "_"),
                if important { "!" } else { "" }
            );
            return base_utility(&lowered, resolve).map(Some);
        }
    }
    if let Some(token) = class
        .strip_prefix("shadow-")
        .filter(|token| *token != "none")
    {
        let name = format!("--shadow-{token}");
        if has(&name) {
            let value = resolve("box-shadow", &reference(&name))?;
            let parsed = crate::style::parse_property("box-shadow", &value)
                .map_err(TailwindClassError::Css)?;
            let mut layers = Vec::new();
            for declaration in parsed.declarations.iter() {
                if let takumi_core::style::StyleDeclaration::BoxShadow(Some(shadows)) = declaration
                {
                    for shadow in shadows.iter() {
                        layers.push(format!(
                            "{}{} {} {} {} var(--tw-shadow-color,{})",
                            if shadow.inset { "inset " } else { "" },
                            shadow.offset_x.to_css_string(),
                            shadow.offset_y.to_css_string(),
                            shadow.blur_radius.to_css_string(),
                            shadow.spread_radius.to_css_string(),
                            shadow.color.to_css_string()
                        ));
                    }
                }
            }
            let value = if layers.is_empty() {
                "none".into()
            } else {
                layers.join(",")
            };
            let declarations = format!(
                "box-shadow:{value}{};",
                if important { " !important" } else { "" }
            );
            return Ok(Some(Utility {
                candidate: candidate.into(),
                order: declaration_order(&declarations),
                declarations,
                inline_display: None,
            }));
        }
    }
    for (prefix, property) in [
        ("border-r-", "border-right-color"),
        ("border-b-", "border-bottom-color"),
        ("border-l-", "border-left-color"),
        ("border-x-", "border-color"),
        ("border-y-", "border-color"),
        ("border-", "border-color"),
        ("outline-", "outline-color"),
        ("decoration-", "text-decoration-color"),
        ("bg-", "background-color"),
        ("text-", "color"),
        ("from-", "color"),
        ("via-", "color"),
        ("to-", "color"),
        ("shadow-", "color"),
        ("text-shadow-", "color"),
    ] {
        let Some(token) = class.strip_prefix(prefix) else {
            continue;
        };
        let (token, alpha) = token
            .split_once('/')
            .map_or((token, None), |(t, a)| (t, Some(a)));
        let name = format!("--color-{token}");
        if matches!(token, "transparent" | "current" | "inherit") {
            continue;
        }
        if (prefix == "shadow-"
            && matches!(
                token,
                "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl"
            ))
            || (prefix == "text-shadow-"
                && matches!(token, "none" | "2xs" | "xs" | "sm" | "md" | "lg"))
        {
            // Shadow geometry tokens take precedence over colors with the same name.
            continue;
        }
        if has(&name) {
            let value = resolve(property, &reference(&name))?;
            let value = if let Some(alpha) = alpha {
                if !super::non_negative_number(alpha)
                    || alpha.parse::<f64>().is_ok_and(|v| v > 100.0)
                {
                    return Err(TailwindClassError::Unsupported);
                }
                format!("color-mix(in oklab,{value} {alpha}%,transparent)")
            } else {
                value
            };
            if matches!(
                prefix,
                "from-" | "via-" | "to-" | "shadow-" | "text-shadow-"
            ) {
                use takumi_core::style::FromCssStr;
                crate::style::parse_property("color", &value).map_err(TailwindClassError::Css)?;
                let color = takumi_core::style::ColorInput::from_css_str(&value)
                    .map_err(|_| TailwindClassError::Unsupported)?;
                let color = color.to_css_string().replace(' ', "_");
                let declarations = format!(
                    "@apply {prefix}[{color}]{};",
                    if important { "!" } else { "" }
                );
                StyleSheet::parse(&format!(".utility{{{declarations}}}"))
                    .map_err(|_| TailwindClassError::Unsupported)?;
                return Ok(Some(Utility {
                    candidate: candidate.into(),
                    order: declaration_order(&declarations),
                    declarations,
                    inline_display: None,
                }));
            }
            let values = match prefix {
                "border-x-" => vec![
                    ("border-left-color".into(), value.clone()),
                    ("border-right-color".into(), value),
                ],
                "border-y-" => vec![
                    ("border-top-color".into(), value.clone()),
                    ("border-bottom-color".into(), value),
                ],
                _ => vec![(property.into(), value)],
            };
            return css(values);
        }
    }
    Ok(None)
}

/// Split a modifier only outside quoted, escaped or nested arbitrary values.
fn modifier_at(source: &str) -> Option<usize> {
    let mut depth = 0u32;
    let mut escaped = false;
    let mut quote = None;
    for (at, ch) in source.char_indices() {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' {
            escaped = true;
            continue;
        }
        if let Some(end) = quote {
            if ch == end {
                quote = None;
            }
            continue;
        }
        match ch {
            '\'' | '"' => quote = Some(ch),
            '[' | '(' => depth += 1,
            ']' | ')' => depth = depth.saturating_sub(1),
            '/' if depth == 0 => return Some(at),
            _ => {}
        }
    }
    None
}

/// Tailwind's custom-property shorthand (`w-(--size)`, `text-(length:--size)/(--leading)`) is a
/// boundary now: there is no variable environment to consume it from. Detect it precisely so the
/// message can name the replacement instead of reporting an unknown utility.
fn reject_variable_shorthand(candidate: &str) -> Result<(), TailwindClassError> {
    let variable_boundary = |value: &str| {
        TailwindClassError::Css(
            crate::style::StyleIssue::new(
                crate::style::StyleIssueKind::UnsupportedValue,
                candidate,
                value,
                "the custom-property shorthand has no variable environment",
            )
            .with_suggestion("a literal value, or an arbitrary value with a `const` interpolated"),
        )
    };
    let (class, _) = candidate
        .strip_suffix('!')
        .map_or((candidate, ""), |class| (class, "!"));
    let (base, modifier) =
        modifier_at(class).map_or((class, None), |at| (&class[..at], Some(&class[at + 1..])));
    // Report the variable name itself: the surrounding shorthand syntax is already in the class
    // name the message is prefixed with.
    fn variable_name(raw: &str) -> &str {
        raw.trim_matches(['(', ')'])
    }
    if let Some((prefix, raw)) = base.split_once("-(")
        && prefix
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '-')
    {
        return Err(variable_boundary(variable_name(raw)));
    }
    if let Some(modifier) = modifier
        && modifier.starts_with('(')
        && modifier.ends_with(')')
    {
        return Err(variable_boundary(variable_name(modifier)));
    }
    Ok(())
}

fn extra_utility(
    class: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Option<Css>, TailwindClassError> {
    let one = |property: &str, value: String| Some(vec![(property.into(), value)]);
    if class == "leading-none" {
        return Ok(one("line-height", "1".into()));
    }
    if matches!(class, "font-sans" | "font-serif" | "font-mono") {
        return Ok(one(
            "font-family",
            default_theme(&format!("--{class}"))
                .expect("generated font family default")
                .into(),
        ));
    }
    if let Some(value) = class
        .strip_prefix("max-w-")
        .and_then(|token| default_theme(&format!("--container-{token}")))
    {
        return Ok(one("max-width", value.into()));
    }
    if let Some(css) = text_with_leading(class, resolve)? {
        return Ok(Some(css));
    }
    // A slash inside an arbitrary CSS value is not a utility fraction/modifier.
    if class.contains('[') {
        return arbitrary(class, resolve).map(|value| value.and_then(|(css, _)| css));
    }
    if class == "tabular-nums" {
        return Ok(one("font-variant-numeric", "tabular-nums".into()));
    }
    if class == "self-auto" {
        return Ok(one("align-self", "auto".into()));
    }
    // Numeric flex is the `flex: N` shorthand (its basis is 0%, not 0px).
    for (prefix, property) in [
        ("flex-", "flex"),
        ("grow-", "flex-grow"),
        ("shrink-", "flex-shrink"),
    ] {
        if let Some(value) = class
            .strip_prefix(prefix)
            .filter(|v| super::non_negative_number(v))
        {
            return Ok(one(property, value.into()));
        }
    }
    if matches!(class, "grow" | "shrink") {
        return Ok(one(
            if class == "grow" {
                "flex-grow"
            } else {
                "flex-shrink"
            },
            "1".into(),
        ));
    }
    for (prefix, property) in [("order-", "order"), ("z-", "z-index")] {
        let (negative, token) = class
            .strip_prefix('-')
            .map_or((false, class), |v| (true, v));
        if let Some(value) = token.strip_prefix(prefix) {
            if value.bytes().all(|byte| byte.is_ascii_digit())
                && let Ok(value) = value.parse::<i32>()
            {
                return Ok(one(
                    property,
                    (if negative {
                        -(i64::from(value))
                    } else {
                        i64::from(value)
                    })
                    .to_string(),
                ));
            }
            if !negative && value == "auto" && property == "z-index" {
                return Ok(one(property, "auto".into()));
            }
            if !negative && value == "none" && property == "order" {
                return Ok(one(property, "0".into()));
            }
        }
    }
    for (prefix, property) in [
        ("justify-items-", "justify-items"),
        ("justify-self-", "justify-self"),
        ("place-items-", "place-items"),
        ("place-content-", "place-content"),
        ("place-self-", "place-self"),
    ] {
        if let Some(value) = class.strip_prefix(prefix).filter(|v| {
            matches!(
                *v,
                "auto"
                    | "normal"
                    | "start"
                    | "end"
                    | "center"
                    | "stretch"
                    | "baseline"
                    | "between"
                    | "around"
                    | "evenly"
            )
        }) {
            let value = if matches!(value, "between" | "around" | "evenly") {
                format!("space-{value}")
            } else {
                value.into()
            };
            return Ok(one(property, value));
        }
    }
    if let Some(value) = class.strip_prefix("object-") {
        if matches!(value, "contain" | "cover" | "fill" | "none" | "scale-down") {
            return Ok(one("object-fit", value.into()));
        }
        if matches!(
            value,
            "center"
                | "top"
                | "right"
                | "bottom"
                | "left"
                | "left-top"
                | "left-bottom"
                | "right-top"
                | "right-bottom"
        ) {
            return Ok(one("object-position", value.replace('-', " ")));
        }
    }
    if let Some(value) = class
        .strip_prefix("text-")
        .filter(|v| matches!(*v, "wrap" | "nowrap" | "balance" | "pretty"))
    {
        return Ok(one("text-wrap", value.into()));
    }
    for (prefix, property) in [
        ("w-", "width"),
        ("h-", "height"),
        ("basis-", "flex-basis"),
        ("min-w-", "min-width"),
        ("max-w-", "max-width"),
        ("min-h-", "min-height"),
        ("max-h-", "max-height"),
    ] {
        if let Some((a, b)) = class.strip_prefix(prefix).and_then(|v| v.split_once('/')) {
            if let (Ok(a), Ok(b)) = (a.parse::<u32>(), b.parse::<u32>()) {
                if b > 0 {
                    return Ok(one(
                        property,
                        format!("{}%", f64::from(a) / f64::from(b) * 100.0),
                    ));
                }
            }
            return Err(TailwindClassError::Unsupported);
        }
    }
    Ok(None)
}
fn base_utility(
    candidate: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Utility, TailwindClassError> {
    let important = candidate.ends_with('!');
    let class = candidate.strip_suffix('!').unwrap_or(candidate);
    if class.ends_with('!') {
        return Err(TailwindClassError::Unsupported);
    }
    if class.starts_with('[') {
        let (property, raw) = arbitrary_property_parts(class).ok_or(TailwindClassError::Syntax(
            "expected [property:value] with a nonempty property and value",
        ))?;
        let value = resolve(property, &decode_arbitrary(raw)?)?;
        let inline_display = if property == "display" {
            let parsed =
                crate::style::parse_property(property, &value).map_err(TailwindClassError::Css)?;
            parsed
                .declarations
                .iter()
                .any(|d| {
                    matches!(
                        d,
                        takumi_core::style::StyleDeclaration::Display(
                            takumi_core::style::Display::Inline
                        )
                    )
                })
                .then_some(important || !parsed.declarations.importance.is_empty())
        } else {
            None
        };
        let declarations = css_declarations(&[(property.into(), value)], important)?;
        return Ok(Utility {
            candidate: candidate.into(),
            declarations,
            order: declaration_order(&format!("{property}:1;")),
            inline_display,
        });
    }
    if let Some(visual) = super::visual::utility(class, resolve)? {
        let order = pair_order(&visual.declarations);
        let declarations = visual
            .declarations
            .into_iter()
            .map(|(property, value)| {
                // Takumi's stylesheet parser includes `!important` in custom-property
                // values. Separate private slots preserve their priority without feeding
                // that marker into var() substitution; normal properties use CSS importance.
                if important && let Some(slot) = property.strip_prefix("--tw-") {
                    return format!("--tw-important-{slot}:{value};");
                }
                format!(
                    "{property}:{value}{};",
                    if important { " !important" } else { "" }
                )
            })
            .collect::<String>();
        StyleSheet::parse(&format!(".utility{{{declarations}}}"))
            .map_err(|_| TailwindClassError::Unsupported)?;
        return Ok(Utility {
            candidate: candidate.into(),
            order,
            declarations,
            inline_display: None,
        });
    }
    let css = extra_utility(class, resolve)?;
    if css.is_none() {
        validate_catalog_class(class)?;
    }
    let order = css.as_ref().map(pair_order);
    let declarations = if let Some(css) = css {
        if class.starts_with("leading-") {
            typography_declarations(&css, important, true)?
        } else {
            css_declarations(&css, important)?
        }
    } else {
        format!("@apply {class}{};", if important { "!" } else { "" })
    };
    // @apply is strict, unlike TailwindValues::from_str's filter_map of unknown tokens.
    StyleSheet::parse(&format!(".utility{{{declarations}}}"))
        .map_err(|_| TailwindClassError::Unsupported)?;
    Ok(Utility {
        candidate: candidate.into(),
        order: order.unwrap_or_else(|| declaration_order(&declarations)),
        declarations,
        inline_display: (class == "inline").then_some(important),
    })
}

/// Text-scale companions consume explicit typography utility slots, even when the
/// scale itself is important. The private slots do not inherit to child nodes.
fn typography_declarations(
    css: &[(String, String)],
    important: bool,
    set_slots: bool,
) -> Result<String, TailwindClassError> {
    let mut output = String::new();
    for (property, value) in css {
        let slot = match property.as_str() {
            "line-height" => "leading",
            "letter-spacing" => "tracking",
            "font-weight" => "font-weight",
            _ => {
                output.push_str(&css_declarations(
                    &[(property.clone(), value.clone())],
                    important,
                )?);
                continue;
            }
        };
        let parsed =
            crate::style::parse_property(property, value).map_err(TailwindClassError::Css)?;
        let important = important || !parsed.declarations.importance.is_empty();
        let declaration = parsed
            .declarations
            .iter()
            .next()
            .ok_or(TailwindClassError::Unsupported)?
            .to_css_string();
        let (_, value) = declaration
            .trim_end_matches(';')
            .split_once(':')
            .ok_or(TailwindClassError::Unsupported)?;
        let value = value.trim();
        let final_value = if set_slots {
            output.push_str(&format!(
                "--tw-{}{slot}:{value};",
                if important { "important-" } else { "" }
            ));
            value.to_owned()
        } else {
            format!("var(--tw-important-{slot},var(--tw-{slot},{value}))")
        };
        output.push_str(&format!(
            "{property}:{final_value}{};",
            if important { " !important" } else { "" }
        ));
    }
    StyleSheet::parse(&format!(".utility{{{output}}}"))
        .map_err(|_| TailwindClassError::Unsupported)?;
    Ok(output)
}

/// Inspect decoded CSS tokens, so quotes and CSS escapes cannot hide a resource URI.
fn font_value_uses_asset(value: &str) -> bool {
    use cssparser::Token;
    let mut input = cssparser::ParserInput::new(value);
    let mut parser = cssparser::Parser::new(&mut input);
    while let Ok(token) = parser.next() {
        if matches!(token, Token::QuotedString(name) if name.starts_with("asset://")) {
            return true;
        }
    }
    false
}

pub(crate) fn css_declarations(
    css: &[(String, String)],
    important: bool,
) -> Result<String, TailwindClassError> {
    let fail = TailwindClassError::Unsupported;
    let mut result = String::new();
    for (property, value) in css {
        if property.starts_with("--") {
            return Err(TailwindClassError::Css(crate::style::StyleIssue::new(
                crate::style::StyleIssueKind::UnsupportedProperty,
                property,
                value,
                "custom-property utilities require conditional variable cascade lowering; declare static variables in style for now",
            )));
        }
        if crate::style::contains_variable(value) {
            return Err(TailwindClassError::Css(crate::style::StyleIssue::new(
                crate::style::StyleIssueKind::UnsupportedValue,
                property,
                value,
                "authored variables need the shared variable resolver; use a resolved CSS value",
            )));
        }
        let parsed =
            crate::style::parse_property(property, value).map_err(TailwindClassError::Css)?;
        if matches!(property.as_str(), "font-family" | "font") && font_value_uses_asset(value) {
            return Err(TailwindClassError::Css(
                crate::style::StyleIssue::new(
                    crate::style::StyleIssueKind::UnsupportedValue,
                    property,
                    value,
                    "resource fonts cannot be bound from a utility; use style.fontFamily",
                )
                .with_suggestion("`style={{ fontFamily: \"asset://brand\" }}`"),
            ));
        }
        if matches!(property.as_str(), "background" | "background-image")
            && !crate::style::gradient_background_source(property, value)
        {
            return Err(TailwindClassError::Css(crate::style::StyleIssue::new(
                crate::style::StyleIssueKind::UnsupportedValue,
                property,
                value,
                "background requires a supported color or sRGB gradient; URL images and other interpolation spaces have no paint lowering",
            )));
        }
        let authored_important = !parsed.declarations.importance.is_empty();
        let important = important || authored_important;
        if matches!(property.as_str(), "font-family" | "font")
            && parsed.declarations.iter().any(|declaration| {
                matches!(
                    declaration,
                    takumi_core::style::StyleDeclaration::FontFamily(_)
                )
            })
        {
            // Takumi's FontFamily serializer maps ui-serif/ui-monospace to sans-serif
            // and drops quotes around names such as 'serif'. Its stylesheet list parser
            // also consumes !important as a family token. Preserve the validated value
            // through the same private priority slots used by visual utilities.
            let mut input = cssparser::ParserInput::new(value);
            let mut input = cssparser::Parser::new(&mut input);
            let raw = input
                .parse_until_before(cssparser::Delimiter::Bang, |input| {
                    let start = input.position();
                    while input.next_including_whitespace_and_comments().is_ok() {}
                    Ok::<_, cssparser::ParseError<'_, ()>>(input.slice_from(start).trim())
                })
                .map_err(|_| fail.clone())?;
            let slot = format!(
                "--tw-{}{property}",
                if important { "important-" } else { "" }
            );
            result.push_str(&format!(
                "{slot}:{raw};{property}:var({slot}){};",
                if important { " !important" } else { "" }
            ));
            continue;
        }
        for declaration in parsed.declarations.iter() {
            // Presence slots follow the same separate priority bank as visual utilities.
            if let takumi_core::style::StyleDeclaration::CustomProperty(name, value) = declaration {
                let name = if important && !name.starts_with("--tw-important-") {
                    name.replacen("--tw-", "--tw-important-", 1)
                } else {
                    name.clone()
                };
                result.push_str(&format!("{name}:{value};"));
                continue;
            }
            let css = declaration.to_css_string();
            result.push_str(css.trim_end_matches(';'));
            if important {
                result.push_str(" !important");
            }
            result.push(';');
        }
    }
    StyleSheet::parse(&format!(".utility{{{result}}}")).map_err(|_| fail.clone())?;
    Ok(result)
}

fn length_math(value: &str) -> bool {
    let mut input = cssparser::ParserInput::new(value);
    let mut input = cssparser::Parser::new(&mut input);
    matches!(input.next(), Ok(cssparser::Token::Function(name)) if matches!(name.as_ref(), "calc" | "min" | "max" | "clamp"))
}

fn arbitrary(
    class: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Option<(Option<Css>, String)>, TailwindClassError> {
    let fail = TailwindClassError::Unsupported;
    let (negative, class) = class
        .strip_prefix('-')
        .map_or((false, class), |class| (true, class));
    let (prefix, raw) = class.split_once("-[").ok_or_else(|| fail.clone())?;
    let raw = raw.strip_suffix(']').ok_or_else(|| fail.clone())?;
    let mut value = decode_arbitrary(raw)?;
    if negative {
        if !matches!(
            prefix,
            "m" | "mx"
                | "my"
                | "mt"
                | "mr"
                | "mb"
                | "ml"
                | "ms"
                | "me"
                | "inset"
                | "inset-x"
                | "inset-y"
                | "top"
                | "right"
                | "bottom"
                | "left"
        ) {
            return Err(fail.clone());
        }
        value = format!("calc({value} * -1)");
    }
    if prefix == "size" {
        return Ok(Some((
            Some(vec![
                ("width".into(), resolve("width", &value)?),
                ("height".into(), resolve("height", &value)?),
            ]),
            "size-4".into(),
        )));
    }
    let (property, sample) = match prefix {
        "px" => ("padding-inline", "px-4"),
        "py" => ("padding-block", "py-4"),
        "pt" => ("padding-top", "pt-4"),
        "pr" => ("padding-right", "pr-4"),
        "pb" => ("padding-bottom", "pb-4"),
        "pl" => ("padding-left", "pl-4"),
        "ps" => ("padding-inline-start", "ps-4"),
        "pe" => ("padding-inline-end", "pe-4"),
        "mx" => ("margin-inline", "mx-4"),
        "my" => ("margin-block", "my-4"),
        "mt" => ("margin-top", "mt-4"),
        "mr" => ("margin-right", "mr-4"),
        "mb" => ("margin-bottom", "mb-4"),
        "ml" => ("margin-left", "ml-4"),
        "ms" => ("margin-inline-start", "ms-4"),
        "me" => ("margin-inline-end", "me-4"),
        "inset" => ("inset", "inset-4"),
        "inset-x" => ("inset-inline", "inset-x-4"),
        "inset-y" => ("inset-block", "inset-y-4"),
        "gap-x" => ("column-gap", "gap-x-4"),
        "gap-y" => ("row-gap", "gap-y-4"),
        "leading" => ("line-height", "leading-[1.4]"),
        "w" => ("width", "w-[13px]"),
        "h" => ("height", "h-4"),
        "min-w" => ("min-width", "min-w-4"),
        "max-w" => ("max-width", "max-w-4"),
        "min-h" => ("min-height", "min-h-4"),
        "max-h" => ("max-height", "max-h-4"),
        "basis" => ("flex-basis", "basis-4"),
        "p" => ("padding", "p-4"),
        "m" => ("margin", "m-4"),
        "gap" => ("gap", "gap-4"),
        "top" => ("top", "top-4"),
        "right" => ("right", "right-4"),
        "bottom" => ("bottom", "bottom-4"),
        "left" => ("left", "left-4"),
        "grid-cols" => ("grid-template-columns", "grid-cols-4"),
        "grid-rows" => ("grid-template-rows", "grid-rows-4"),
        "aspect" => ("aspect-ratio", "aspect-[4/3]"),
        "bg" => ("background-color", "bg-[#123456]"),
        "text" => {
            if let Some(v) = value.strip_prefix("length:") {
                value = v.into();
                ("font-size", "text-[13px]")
            } else if let Some(v) = value.strip_prefix("color:") {
                value = v.into();
                ("color", "text-red-500")
            } else if (crate::style::contains_variable(&value) && !length_math(&value))
                || crate::style::parse_property("color", &value).is_ok()
            {
                ("color", "text-red-500")
            } else {
                ("font-size", "text-[13px]")
            }
        }
        _ => return Err(fail.clone()),
    };
    Ok(Some((
        Some(vec![(property.into(), resolve(property, &value)?)]),
        sample.into(),
    )))
}

pub(super) fn decode_arbitrary(raw: &str) -> Result<String, TailwindClassError> {
    super::arbitrary::decode(raw)
}

fn text_with_leading(
    class: &str,
    resolve: &ValueResolver<'_>,
) -> Result<Option<Css>, TailwindClassError> {
    let Some(text) = class.strip_prefix("text-") else {
        return Ok(None);
    };
    let Some(at) = modifier_at(text) else {
        return Ok(None);
    };
    let (size, leading) = (&text[..at], &text[at + 1..]);
    let size = if let Some(raw) = size.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        let value = decode_arbitrary(raw)?;
        value.strip_prefix("length:").unwrap_or(&value).to_owned()
    } else if let Some(value) = default_theme(&format!("--text-{size}")) {
        value.into()
    } else {
        return Ok(None);
    };
    // A color with an opacity modifier is not a font-size/line-height utility.
    if size.starts_with("color:")
        || crate::style::parse_property("color", &size).is_ok()
        || (crate::style::contains_variable(&size)
            && !length_math(&size)
            && !text.starts_with("[length:"))
    {
        return Ok(None);
    }
    let size = resolve("font-size", &size)?;
    crate::style::parse_property("font-size", &size).map_err(TailwindClassError::Css)?;
    let leading = if let Some(raw) = leading.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        decode_arbitrary(raw)?
    } else if super::non_negative_number(leading) {
        format!("calc(0.25rem * {leading})")
    } else {
        return Err(TailwindClassError::Unsupported);
    };
    Ok(Some(vec![
        ("font-size".into(), size),
        ("line-height".into(), resolve("line-height", &leading)?),
    ]))
}

// Conflict order, kept in the shape of the upstream `compileCandidates` sort: property indices
// (missing is infinity), decreasing declaration count, then alphanumeric candidate order. Every
// key comes from `order_table::PROPERTY_ORDER` and the declarations this module emits, never from
// the authored class string.
fn compare_utilities(a: &Utility, b: &Utility) -> Ordering {
    for i in 0..a.order.order.len().max(b.order.order.len()) {
        let order = a
            .order
            .order
            .get(i)
            .unwrap_or(&u16::MAX)
            .cmp(b.order.order.get(i).unwrap_or(&u16::MAX));
        if order != Ordering::Equal {
            return order;
        }
    }
    b.order
        .count
        .cmp(&a.order.count)
        .then_with(|| natural_compare(&a.candidate, &b.candidate))
}

fn natural_compare(a: &str, b: &str) -> Ordering {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    let (mut i, mut j) = (0, 0);
    while i < a.len() && j < b.len() {
        if a[i].is_ascii_digit() && b[j].is_ascii_digit() {
            let (start_i, start_j) = (i, j);
            while i < a.len() && a[i].is_ascii_digit() {
                i += 1;
            }
            while j < b.len() && b[j].is_ascii_digit() {
                j += 1;
            }
            let aa = std::str::from_utf8(&a[start_i..i])
                .unwrap()
                .trim_start_matches('0');
            let bb = std::str::from_utf8(&b[start_j..j])
                .unwrap()
                .trim_start_matches('0');
            let order = aa.len().cmp(&bb.len()).then_with(|| aa.cmp(bb));
            if order != Ordering::Equal {
                return order;
            }
        } else {
            let order = a[i].cmp(&b[j]);
            if order != Ordering::Equal {
                return order;
            }
            i += 1;
            j += 1;
        }
    }
    a.len().cmp(&b.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_order_is_stable_under_class_reversal() {
        let corpus: Vec<_> = super::super::FIXED
            .iter()
            .copied()
            .filter_map(|name| utility(name).ok())
            .collect();
        assert!(
            corpus.len() >= 80,
            "the fixed catalog must expand for the reversal check to mean anything"
        );
        let mut expected = corpus.clone();
        expected.sort_by(compare_utilities);
        let mut reversed = expected.clone();
        reversed.reverse();
        reversed.sort_by(compare_utilities);
        assert_eq!(
            reversed.iter().map(|u| &u.candidate).collect::<Vec<_>>(),
            expected.iter().map(|u| &u.candidate).collect::<Vec<_>>(),
            "the catalog order must be a total order independent of the authored order"
        );
    }

    #[test]
    fn every_catalog_fixture_expands_instead_of_being_silently_ignored() {
        let missing: Vec<_> = super::super::FIXED
            .iter()
            .copied()
            .filter(|candidate| {
                validate_catalog_class(candidate).is_ok() && utility(candidate).is_err()
            })
            .collect();
        assert!(missing.is_empty(), "unexpanded catalog: {missing:?}");
    }
}

/// Reject a utility that carries a variant prefix.
///
/// Balanced brackets, quotes, escapes and comments are scanned first so a colon *inside* an
/// arbitrary value (`[background:url(a:b)]`) is still part of the value. The signature is
/// deliberately narrower than the previous splitter: after the convergence there are no variants to
/// interpret, only this boundary to report.
fn reject_variants(candidate: &str) -> Result<&str, TailwindClassError> {
    let fail = || {
        TailwindClassError::Syntax(
            "utility variants and arbitrary values require balanced brackets, quotes and escapes",
        )
    };
    let mut stack = Vec::new();
    let mut quote = None;
    let mut escaped = false;
    let mut at_start = true;
    let mut chars = candidate.char_indices().peekable();
    while let Some((_, ch)) = chars.next() {
        if escaped {
            escaped = false;
            at_start = false;
            continue;
        }
        if ch == '\\' {
            escaped = true;
            continue;
        }
        if let Some(end) = quote {
            if ch == end {
                quote = None;
            }
            continue;
        }
        if ch == '/' && chars.peek().is_some_and(|(_, ch)| *ch == '*') {
            chars.next();
            let mut closed = false;
            while let Some((_, ch)) = chars.next() {
                if ch == '*' && chars.peek().is_some_and(|(_, ch)| *ch == '/') {
                    chars.next();
                    closed = true;
                    break;
                }
            }
            if !closed {
                return Err(fail());
            }
            continue;
        }
        match ch {
            '\'' | '"' => quote = Some(ch),
            '[' | '(' => {
                if stack.len() >= 64 {
                    return Err(fail());
                }
                stack.push(if ch == '[' { ']' } else { ')' });
            }
            ']' | ')' => {
                if stack.pop() != Some(ch) {
                    return Err(fail());
                }
            }
            ':' if stack.is_empty() => {
                if at_start {
                    return Err(fail());
                }
                return Err(TailwindClassError::Forbidden);
            }
            _ => {}
        }
        at_start = false;
    }
    if quote.is_some() || !stack.is_empty() {
        return Err(fail());
    }
    Ok(candidate)
}

#[cfg(test)]
mod order_golden {
    use super::*;

    /// Conflict groups whose resolution must not drift. The order is the stylesheet order, so the
    /// last candidate wins; each group is a pair an author could reasonably write together.
    const GOLDEN: &[(&[&str], &[&str])] = &[
        (&["p-4", "px-2"], &["p-4", "px-2"]),
        (&["p-4", "pt-2"], &["p-4", "pt-2"]),
        (&["w-4", "w-8"], &["w-4", "w-8"]),
        (&["w-4", "min-w-8"], &["w-4", "min-w-8"]),
        (&["text-sm", "text-lg"], &["text-lg", "text-sm"]),
        (&["text-sm", "leading-8"], &["text-sm", "leading-8"]),
        (&["shadow-sm", "shadow-lg"], &["shadow-lg", "shadow-sm"]),
        (
            &["bg-red-500", "bg-blue-500"],
            &["bg-blue-500", "bg-red-500"],
        ),
        (
            &["translate-x-1", "translate-x-2"],
            &["translate-x-1", "translate-x-2"],
        ),
        (&["scale-95", "scale-105"], &["scale-95", "scale-105"]),
        (&["rotate-45", "rotate-90"], &["rotate-45", "rotate-90"]),
        (&["blur-sm", "blur-lg"], &["blur-lg", "blur-sm"]),
        // Same slot and same write count, so the name decides and the value outlives the reset —
        // the frozen corpus pins the same tie for `blur-sm! blur-none!`.
        (&["blur-sm", "blur-none"], &["blur-none", "blur-sm"]),
        (&["blur-[3px]", "blur-none"], &["blur-[3px]", "blur-none"]),
        // A drop shadow value composes two slots upstream, so the reset lands after it.
        (
            &["drop-shadow-sm", "drop-shadow-none"],
            &["drop-shadow-sm", "drop-shadow-none"],
        ),
        // `@apply` utilities carry no generated declarations, so they contribute no property key
        // and sort last: a reset wins here. Documented boundary, not upstream parity.
        (&["shadow-sm", "shadow-none"], &["shadow-sm", "shadow-none"]),
        (&["rounded-sm", "rounded-lg"], &["rounded-lg", "rounded-sm"]),
        (&["z-10", "z-20"], &["z-10", "z-20"]),
        (&["opacity-50", "opacity-90"], &["opacity-50", "opacity-90"]),
        (&["gap-2", "gap-4"], &["gap-2", "gap-4"]),
        (&["font-sans", "font-mono"], &["font-mono", "font-sans"]),
        (&["font-bold", "font-light"], &["font-bold", "font-light"]),
        (
            &["items-start", "items-center"],
            &["items-center", "items-start"],
        ),
        (&["[width:10px]", "w-4"], &["[width:10px]", "w-4"]),
        (
            &["[color:red]", "bg-red-500"],
            &["bg-red-500", "[color:red]"],
        ),
        (&["p-4", "p-[6px]"], &["p-4", "p-[6px]"]),
        (&["w-4", "w-[6px]"], &["w-4", "w-[6px]"]),
    ];

    fn sorted(group: &[&str]) -> Vec<String> {
        let mut utilities = group
            .iter()
            .map(|class| {
                utility(class).unwrap_or_else(|error| panic!("{class}: {}", error.message(class)))
            })
            .collect::<Vec<_>>();
        utilities.sort_by(compare_utilities);
        utilities.into_iter().map(|value| value.candidate).collect()
    }

    #[test]
    fn conflict_resolution_is_pinned() {
        for (group, expected) in GOLDEN {
            assert_eq!(
                sorted(group),
                expected.to_vec(),
                "{group:?} must resolve the same way for every class order"
            );
            let mut reversed = group.to_vec();
            reversed.reverse();
            assert_eq!(
                sorted(&reversed),
                expected.to_vec(),
                "{group:?} must not depend on the class string order"
            );
        }
    }

    /// Every property a utility can emit has a place in the checked-in order table. A missing one
    /// would sort by a sentinel index, which is exactly the silent divergence this table prevents.
    #[test]
    fn emitted_properties_are_covered_by_the_table() {
        let corpus = super::super::FIXED.iter().copied().chain([
            "p-4",
            "px-2",
            "py-3",
            "pt-2",
            "m-4",
            "mx-2",
            "w-4",
            "w-1/2",
            "size-4",
            "h-8",
            "basis-1/2",
            "min-w-4",
            "max-w-sm",
            "gap-4",
            "gap-x-2",
            "inset-2",
            "top-4",
            "bg-red-500",
            "text-red-500",
            "text-sm",
            "text-sm/6",
            "leading-4",
            "tracking-wide",
            "font-bold",
            "font-sans",
            "rounded-lg",
            "rounded-t-xl",
            "shadow-lg",
            "shadow-red-500",
            "blur-sm",
            "brightness-110",
            "drop-shadow-sm",
            "backdrop-blur-sm",
            "translate-x-1",
            "-rotate-45",
            "scale-105",
            "origin-top-left",
            "border-2",
            "border-red-500",
            "border-t-4",
            "outline-2",
            "opacity-50",
            "z-10",
            "-order-1",
            "order-none",
            "opacity-50",
            "aspect-video",
            "object-cover",
            "text-wrap",
            "place-items-center",
            "justify-self-end",
            "flex-1",
            "grow",
            "shrink-0",
            "tabular-nums",
            "self-auto",
            "grid-cols-3",
            "grid-flow-col",
            "overflow-hidden",
            "visible",
            "static",
            "w-[6px]",
            "p-[6px]",
            "bg-[#123456]",
            "-left-[20px]",
            "translate-y-[10%]",
            "shadow-[0_1px_2px_#0004]",
        ]);
        let mut missing = Vec::new();
        for class in corpus {
            let Ok(utility) = utility(class) else {
                continue;
            };
            for property in declaration_properties(&utility.declarations) {
                if property.starts_with("--tw-") {
                    continue;
                }
                if order_table::index(&property).is_none() {
                    missing.push(format!("{class} -> {property}"));
                }
            }
        }
        assert!(
            missing.is_empty(),
            "these utilities emit a property missing from PROPERTY_ORDER: {missing:?}"
        );
    }
}
