// @generated by valle-timeline schema-gen; do not edit.
// Source: Rust wire DTOs -> schemars 1.2.2 (Draft 2020-12).
// Surface: public author/edit.
// Runtime validation and canonicalization remain in Rust/WASM.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export namespace TimelineSchema {
  export type Root = { "canvas": TimelineCanvasWire; "resources"?: Record<string, string>; "tracks": TimelineTracksWire };
  export type BlendModeWire = ("normal" | "screen" | "lighten" | "color-dodge" | "multiply" | "darken" | "color-burn" | "linear-burn" | "overlay" | "soft-light" | "hard-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity");
  export type CaptionAlignWire = ("top-left" | "top-center" | "top-right" | "center-left" | "center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right");
  export type CubicBezierEasingWire = { "type": CubicBezierTag; "x1": number; "x2": number; "y1": number; "y2": number };
  export type CubicBezierTag = "cubic-bezier";
  export type DisplayCaptionPresetName = ("breathe" | "float" | "sway" | "pulse" | "shake");
  export type EasingWire = (NamedEasingWire | CubicBezierEasingWire);
  export type EnterCaptionPresetName = ("fade" | "slide-up" | "slide-down" | "slide-left" | "slide-right" | "pop" | "zoom-in" | "zoom-out" | "focus" | "wipe-right" | "wipe-left");
  export type ExitCaptionPresetName = ("fade" | "slide-up" | "slide-down" | "slide-left" | "slide-right" | "pop" | "zoom-in" | "zoom-out" | "focus" | "wipe-right" | "wipe-left");
  export type InterpolationWire = ("step" | "linear");
  export type KaraokeModeWire = ("word" | "line");
  export type MediaEndBehaviorWire = ("error" | "hold" | "loop");
  export type NamedEasingWire = ("linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out");
  export type RasterFitWire = ("contain" | "cover" | "fill" | "none");
  export type ScrollAxisWire = ("horizontal" | "vertical");
  export type TimelineAdjustmentClipWire = ({ "duration": TimelineTimeWire; "start": TimelineTimeWire } & { "kind": "color-grade"; "temperature": number });
  export type TimelineAdjustmentTrackWire = { "clips": Array<TimelineAdjustmentClipWire> };
  export type TimelineAudioClipWire = { "duration": TimelineTimeWire; "end"?: (MediaEndBehaviorWire | null); "gain"?: (TimelineParamWire | null); "pan"?: (TimelineParamWire | null); "rate"?: (TimelineTimeWire | null); "src": string; "start": TimelineTimeWire; "trimStart"?: (TimelineTimeWire | null) };
  export type TimelineAudioTrackWire = { "clips": Array<TimelineAudioClipWire> };
  export type TimelineCanvasWire = { "background"?: (string | null); "fps": TimelineFrameRateWire; "height": number; "width": number };
  export type TimelineCaptionBehaviorWire = ({ "axis": ScrollAxisWire; "speed": number; "type": "scroll" } | { "mode": KaraokeModeWire; "type": "karaoke" });
  export type TimelineCaptionClipWire = { "behavior"?: (TimelineCaptionBehaviorWire | null); "display"?: (TimelineDisplayPresetWire | null); "duration": TimelineTimeWire; "enter"?: (TimelineEnterPresetWire | null); "exit"?: (TimelineExitPresetWire | null); "layout"?: (TimelineCaptionLayoutWire | null); "presentation"?: (TimelineCaptionPresentationWire | null); "runs"?: (Array<TimelineTextRunWire> | null); "start": TimelineTimeWire; "text"?: (string | null) };
  export type TimelineCaptionLayoutWire = { "align"?: (CaptionAlignWire | null); "region"?: ([number, number, number, number] | null) };
  export type TimelineCaptionPresentationWire = { "blur"?: (TimelineParamWire | null); "clipInset"?: (TimelineParamWire4 | null); "opacity"?: (TimelineParamWire | null); "rotation"?: (TimelineParamWire | null); "scale"?: (TimelineParamWire | null); "translation"?: (TimelineParamWire3 | null) };
  export type TimelineCaptionShadowWire = { "blur"?: (number | null); "color": string; "offset": [number, number] };
  export type TimelineCaptionStyleWire = { "color"?: (string | null); "font": string; "fontSize"?: (number | null); "shadow"?: (TimelineCaptionShadowWire | null) };
  export type TimelineCaptionTrackWire = { "clips": Array<TimelineCaptionClipWire>; "layout"?: (TimelineCaptionLayoutWire | null); "style": TimelineCaptionStyleWire };
  export type TimelineCurveWire = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire> };
  export type TimelineCurveWire2 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire2> };
  export type TimelineCurveWire3 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire3> };
  export type TimelineCurveWire4 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire4> };
  export type TimelineDisplayPresetWire = { "preset": DisplayCaptionPresetName; "rate"?: (number | null) };
  export type TimelineEnterPresetWire = { "duration"?: (TimelineTimeWire | null); "preset": EnterCaptionPresetName };
  export type TimelineExitPresetWire = { "duration"?: (TimelineTimeWire | null); "preset": ExitCaptionPresetName };
  export type TimelineFrameRateWire = (number | string);
  export type TimelineKeyframeWire = ([TimelineTimeWire, number] | [TimelineTimeWire, number, EasingWire]);
  export type TimelineKeyframeWire2 = ([TimelineTimeWire, JsonValue] | [TimelineTimeWire, JsonValue, EasingWire]);
  export type TimelineKeyframeWire3 = ([TimelineTimeWire, [number, number]] | [TimelineTimeWire, [number, number], EasingWire]);
  export type TimelineKeyframeWire4 = ([TimelineTimeWire, [number, number, number, number]] | [TimelineTimeWire, [number, number, number, number], EasingWire]);
  export type TimelineMotionCueBindingWire = { "end": TimelineTimeWire; "enterDuration"?: (TimelineTimeWire | null); "exitDuration"?: (TimelineTimeWire | null); "start": TimelineTimeWire; "type": "source-range" };
  export type TimelineMotionPhaseOverridesWire = { "enterDuration"?: (TimelineTimeWire | null); "exitDuration"?: (TimelineTimeWire | null) };
  export type TimelineParamWire = (TimelineCurveWire | number);
  export type TimelineParamWire2 = (TimelineCurveWire2 | JsonValue);
  export type TimelineParamWire3 = (TimelineCurveWire3 | [number, number]);
  export type TimelineParamWire4 = (TimelineCurveWire4 | [number, number, number, number]);
  export type TimelineTextRunWire = { "color"?: (string | null); "end"?: (TimelineTimeWire | null); "fontSize"?: (number | null); "start"?: (TimelineTimeWire | null); "text": string };
  export type TimelineTimeWire = number;
  export type TimelineTracksWire = { "adjustment"?: Array<TimelineAdjustmentTrackWire>; "audio"?: Array<TimelineAudioTrackWire>; "caption"?: Array<TimelineCaptionTrackWire>; "visual"?: Array<TimelineVisualTrackWire> };
  export type TimelineVisualClipWire = ({ "anchor"?: ([number, number] | null); "blend"?: (BlendModeWire | null); "duration": TimelineTimeWire; "opacity"?: (TimelineParamWire | null); "position"?: (TimelineParamWire3 | null); "rotation"?: (TimelineParamWire | null); "scale"?: (TimelineParamWire3 | null); "size"?: (TimelineParamWire3 | null); "start": TimelineTimeWire } & ({ "end"?: (MediaEndBehaviorWire | null); "fit"?: (RasterFitWire | null); "gain"?: (TimelineParamWire | null); "kind": "video"; "rate"?: (TimelineTimeWire | null); "src": string; "trimStart"?: (TimelineTimeWire | null) } | { "fit"?: (RasterFitWire | null); "kind": "image"; "src": string } | { "end"?: (MediaEndBehaviorWire | null); "fit"?: (RasterFitWire | null); "kind": "lottie"; "rate"?: (TimelineTimeWire | null); "src": string; "trimStart"?: (TimelineTimeWire | null) } | { "component": string; "cues"?: Record<string, TimelineMotionCueBindingWire>; "end"?: (MediaEndBehaviorWire | null); "kind": "motion"; "phases"?: (TimelineMotionPhaseOverridesWire | null); "props"?: Record<string, TimelineParamWire2>; "rate"?: (TimelineTimeWire | null); "resources"?: Record<string, string>; "sourceDuration"?: (TimelineTimeWire | null); "trimStart"?: (TimelineTimeWire | null) } | { "color": string; "kind": "solid" }));
  export type TimelineVisualTrackWire = { "clips": Array<TimelineVisualClipWire> };
}
export type Timeline = TimelineSchema.Root;

export namespace EditTimelineRequestSchema {
  export type Root = { "baseRevision": number; "intent"?: (string | null); "timeline": TimelineWire };
  export type BlendModeWire = ("normal" | "screen" | "lighten" | "color-dodge" | "multiply" | "darken" | "color-burn" | "linear-burn" | "overlay" | "soft-light" | "hard-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity");
  export type CaptionAlignWire = ("top-left" | "top-center" | "top-right" | "center-left" | "center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right");
  export type CubicBezierEasingWire = { "type": CubicBezierTag; "x1": number; "x2": number; "y1": number; "y2": number };
  export type CubicBezierTag = "cubic-bezier";
  export type DisplayCaptionPresetName = ("breathe" | "float" | "sway" | "pulse" | "shake");
  export type EasingWire = (NamedEasingWire | CubicBezierEasingWire);
  export type EnterCaptionPresetName = ("fade" | "slide-up" | "slide-down" | "slide-left" | "slide-right" | "pop" | "zoom-in" | "zoom-out" | "focus" | "wipe-right" | "wipe-left");
  export type ExitCaptionPresetName = ("fade" | "slide-up" | "slide-down" | "slide-left" | "slide-right" | "pop" | "zoom-in" | "zoom-out" | "focus" | "wipe-right" | "wipe-left");
  export type InterpolationWire = ("step" | "linear");
  export type KaraokeModeWire = ("word" | "line");
  export type MediaEndBehaviorWire = ("error" | "hold" | "loop");
  export type NamedEasingWire = ("linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out");
  export type RasterFitWire = ("contain" | "cover" | "fill" | "none");
  export type ScrollAxisWire = ("horizontal" | "vertical");
  export type TimelineAdjustmentClipWire = ({ "duration": TimelineTimeWire; "start": TimelineTimeWire } & { "kind": "color-grade"; "temperature": number });
  export type TimelineAdjustmentTrackWire = { "clips": Array<TimelineAdjustmentClipWire> };
  export type TimelineAudioClipWire = { "duration": TimelineTimeWire; "end"?: (MediaEndBehaviorWire | null); "gain"?: (TimelineParamWire | null); "pan"?: (TimelineParamWire | null); "rate"?: (TimelineTimeWire | null); "src": string; "start": TimelineTimeWire; "trimStart"?: (TimelineTimeWire | null) };
  export type TimelineAudioTrackWire = { "clips": Array<TimelineAudioClipWire> };
  export type TimelineCanvasWire = { "background"?: (string | null); "fps": TimelineFrameRateWire; "height": number; "width": number };
  export type TimelineCaptionBehaviorWire = ({ "axis": ScrollAxisWire; "speed": number; "type": "scroll" } | { "mode": KaraokeModeWire; "type": "karaoke" });
  export type TimelineCaptionClipWire = { "behavior"?: (TimelineCaptionBehaviorWire | null); "display"?: (TimelineDisplayPresetWire | null); "duration": TimelineTimeWire; "enter"?: (TimelineEnterPresetWire | null); "exit"?: (TimelineExitPresetWire | null); "layout"?: (TimelineCaptionLayoutWire | null); "presentation"?: (TimelineCaptionPresentationWire | null); "runs"?: (Array<TimelineTextRunWire> | null); "start": TimelineTimeWire; "text"?: (string | null) };
  export type TimelineCaptionLayoutWire = { "align"?: (CaptionAlignWire | null); "region"?: ([number, number, number, number] | null) };
  export type TimelineCaptionPresentationWire = { "blur"?: (TimelineParamWire | null); "clipInset"?: (TimelineParamWire4 | null); "opacity"?: (TimelineParamWire | null); "rotation"?: (TimelineParamWire | null); "scale"?: (TimelineParamWire | null); "translation"?: (TimelineParamWire3 | null) };
  export type TimelineCaptionShadowWire = { "blur"?: (number | null); "color": string; "offset": [number, number] };
  export type TimelineCaptionStyleWire = { "color"?: (string | null); "font": string; "fontSize"?: (number | null); "shadow"?: (TimelineCaptionShadowWire | null) };
  export type TimelineCaptionTrackWire = { "clips": Array<TimelineCaptionClipWire>; "layout"?: (TimelineCaptionLayoutWire | null); "style": TimelineCaptionStyleWire };
  export type TimelineCurveWire = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire> };
  export type TimelineCurveWire2 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire2> };
  export type TimelineCurveWire3 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire3> };
  export type TimelineCurveWire4 = { "interpolation"?: (InterpolationWire | null); "keyframes": Array<TimelineKeyframeWire4> };
  export type TimelineDisplayPresetWire = { "preset": DisplayCaptionPresetName; "rate"?: (number | null) };
  export type TimelineEnterPresetWire = { "duration"?: (TimelineTimeWire | null); "preset": EnterCaptionPresetName };
  export type TimelineExitPresetWire = { "duration"?: (TimelineTimeWire | null); "preset": ExitCaptionPresetName };
  export type TimelineFrameRateWire = (number | string);
  export type TimelineKeyframeWire = ([TimelineTimeWire, number] | [TimelineTimeWire, number, EasingWire]);
  export type TimelineKeyframeWire2 = ([TimelineTimeWire, JsonValue] | [TimelineTimeWire, JsonValue, EasingWire]);
  export type TimelineKeyframeWire3 = ([TimelineTimeWire, [number, number]] | [TimelineTimeWire, [number, number], EasingWire]);
  export type TimelineKeyframeWire4 = ([TimelineTimeWire, [number, number, number, number]] | [TimelineTimeWire, [number, number, number, number], EasingWire]);
  export type TimelineMotionCueBindingWire = { "end": TimelineTimeWire; "enterDuration"?: (TimelineTimeWire | null); "exitDuration"?: (TimelineTimeWire | null); "start": TimelineTimeWire; "type": "source-range" };
  export type TimelineMotionPhaseOverridesWire = { "enterDuration"?: (TimelineTimeWire | null); "exitDuration"?: (TimelineTimeWire | null) };
  export type TimelineParamWire = (TimelineCurveWire | number);
  export type TimelineParamWire2 = (TimelineCurveWire2 | JsonValue);
  export type TimelineParamWire3 = (TimelineCurveWire3 | [number, number]);
  export type TimelineParamWire4 = (TimelineCurveWire4 | [number, number, number, number]);
  export type TimelineTextRunWire = { "color"?: (string | null); "end"?: (TimelineTimeWire | null); "fontSize"?: (number | null); "start"?: (TimelineTimeWire | null); "text": string };
  export type TimelineTimeWire = number;
  export type TimelineTracksWire = { "adjustment"?: Array<TimelineAdjustmentTrackWire>; "audio"?: Array<TimelineAudioTrackWire>; "caption"?: Array<TimelineCaptionTrackWire>; "visual"?: Array<TimelineVisualTrackWire> };
  export type TimelineVisualClipWire = ({ "anchor"?: ([number, number] | null); "blend"?: (BlendModeWire | null); "duration": TimelineTimeWire; "opacity"?: (TimelineParamWire | null); "position"?: (TimelineParamWire3 | null); "rotation"?: (TimelineParamWire | null); "scale"?: (TimelineParamWire3 | null); "size"?: (TimelineParamWire3 | null); "start": TimelineTimeWire } & ({ "end"?: (MediaEndBehaviorWire | null); "fit"?: (RasterFitWire | null); "gain"?: (TimelineParamWire | null); "kind": "video"; "rate"?: (TimelineTimeWire | null); "src": string; "trimStart"?: (TimelineTimeWire | null) } | { "fit"?: (RasterFitWire | null); "kind": "image"; "src": string } | { "end"?: (MediaEndBehaviorWire | null); "fit"?: (RasterFitWire | null); "kind": "lottie"; "rate"?: (TimelineTimeWire | null); "src": string; "trimStart"?: (TimelineTimeWire | null) } | { "component": string; "cues"?: Record<string, TimelineMotionCueBindingWire>; "end"?: (MediaEndBehaviorWire | null); "kind": "motion"; "phases"?: (TimelineMotionPhaseOverridesWire | null); "props"?: Record<string, TimelineParamWire2>; "rate"?: (TimelineTimeWire | null); "resources"?: Record<string, string>; "sourceDuration"?: (TimelineTimeWire | null); "trimStart"?: (TimelineTimeWire | null) } | { "color": string; "kind": "solid" }));
  export type TimelineVisualTrackWire = { "clips": Array<TimelineVisualClipWire> };
  export type TimelineWire = { "canvas": TimelineCanvasWire; "resources"?: Record<string, string>; "tracks": TimelineTracksWire };
}
export type EditTimelineRequest = EditTimelineRequestSchema.Root;

export namespace EditTimelineResponseSchema {
  export type Root = EditTimelineResultWire;
  export type EditErrorWire = { "code": string; "details"?: Record<string, JsonValue>; "path": string };
  export type EditTimelineResultWire = ({ "outcome": "committed"; "revision": number } | { "outcome": "unchanged"; "revision": number } | { "outcome": "staleBase"; "revision": number } | { "errors": Array<EditErrorWire>; "outcome": "rejected" });
}
export type EditTimelineResponse = EditTimelineResponseSchema.Root;
