// @generated by valle-timeline internal schema-gen; do not edit.
// Source: Rust wire DTOs -> schemars 1.2.2 (Draft 2020-12).
// Surface: internal canonical/storage.
// Runtime validation and canonicalization remain in Rust/WASM.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export namespace TimelineDocumentSchema {
  export type Root = { "document": TimelineDocumentWire };
  export type AdjustmentEffectExtensionWire = { "parameters": Record<string, JsonValue>; "type": NamespacedKernelTypeWire };
  export type AdjustmentEffectWire = (ColorGradeEffectWire | AdjustmentEffectExtensionWire);
  export type AudioCompositionWire = { "tracks": Array<AudioTrackWire> };
  export type AudioEffectWire = { "id": string; "parameters": Record<string, JsonValue>; "type": NamespacedKernelTypeWire };
  export type AudioItemWire = ({ "duration": ExactRational; "effects": Array<AudioEffectWire>; "gain": ParamWire2; "id": string; "pan": ParamWire2; "source": AudioSourceWire; "type": "clip" } | { "duration": ExactRational; "id": string; "type": "gap" } | { "duration": ExactRational; "id": string; "type": "crossfade" });
  export type AudioSourceWire = { "endBehavior": MediaEndBehaviorWire; "rate": ExactRational; "resource": string; "sourceStart": ExactRational; "type": "media" };
  export type AudioTrackWire = { "id": string; "items": Array<AudioItemWire> };
  export type BackgroundWire = { "color": string };
  export type BlendModeWire = ("normal" | "screen" | "lighten" | "color-dodge" | "multiply" | "darken" | "color-burn" | "linear-burn" | "overlay" | "soft-light" | "hard-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity");
  export type CameraTrackWire = { "centerX": ParamWire2; "centerY": ParamWire2; "rotation": ParamWire2; "zoom": ParamWire2 };
  export type CanvasWire = { "channelLayout": ChannelLayoutWire; "colorSpace": ColorSpaceWire; "duration": ExactRational; "fps": ExactRational; "height": number; "sampleRate": number; "width": number };
  export type CaptionAlignWire = ("top-left" | "top-center" | "top-right" | "center-left" | "center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right");
  export type CaptionBehaviorWire = ({ "axis": ScrollAxisWire; "speed": number; "type": "scroll" } | { "mode": KaraokeModeWire; "type": "karaoke" });
  export type CaptionCompositionWire = { "tracks": Array<CaptionTrackWire> };
  export type CaptionItemWire = ({ "behavior": RequiredNullable_for_CaptionBehaviorWire; "duration": ExactRational; "id": string; "layout": CaptionLayoutWire; "presentation": CaptionPresentationWire; "runs": Array<TextRunWire>; "style": CaptionStyleWire; "type": "clip" } | { "duration": ExactRational; "id": string; "type": "gap" });
  export type CaptionLayoutWire = { "align": CaptionAlignWire; "region": [number, number, number, number] };
  export type CaptionPresentationWire = { "blurSigma": ParamWire2; "clipInset": ParamWire3; "opacity": ParamWire2; "rotation": ParamWire2; "scale": ParamWire2; "translation": ParamWire };
  export type CaptionShadowWire = { "blurSigma": number; "color": string; "offset": [number, number] };
  export type CaptionStyleWire = { "color": string; "font": string; "fontSize": number; "shadow": RequiredNullable_for_CaptionShadowWire };
  export type CaptionTrackWire = { "id": string; "items": Array<CaptionItemWire> };
  export type ChannelLayoutWire = ("mono" | "stereo");
  export type ColorGradeEffectTag = "color-grade";
  export type ColorGradeEffectWire = { "temperature": number; "type": ColorGradeEffectTag };
  export type ColorSpaceWire = "srgb";
  export type CrossFadeTransitionKernelTag = "cross-fade";
  export type CrossFadeTransitionKernelWire = { "type": CrossFadeTransitionKernelTag };
  export type CubicBezierEasingWire = { "type": CubicBezierTag; "x1": number; "x2": number; "y1": number; "y2": number };
  export type CubicBezierTag = "cubic-bezier";
  export type EasingWire = (NamedEasingWire | CubicBezierEasingWire);
  export type ExactRational = string;
  export type ExtrapolationWire = "clamp";
  export type InterpolationWire = ("step" | "linear");
  export type KaraokeModeWire = ("word" | "line");
  export type KeyframeWire = { "id": string; "outEasing": RequiredNullable_for_EasingWire; "time": ExactRational; "value": [number, number] };
  export type KeyframeWire2 = { "id": string; "outEasing": RequiredNullable_for_EasingWire; "time": ExactRational; "value": number };
  export type KeyframeWire3 = { "id": string; "outEasing": RequiredNullable_for_EasingWire; "time": ExactRational; "value": [number, number, number, number] };
  export type KeyframeWire4 = { "id": string; "outEasing": RequiredNullable_for_EasingWire; "time": ExactRational; "value": JsonValue };
  export type LayerMaskWire = ({ "feather": ParamWire2; "invert": boolean; "rect": ParamWire3; "type": "rect" } | { "feather": ParamWire2; "invert": boolean; "rect": ParamWire3; "type": "ellipse" });
  export type LayerTransformWire = { "anchor": [number, number]; "position": ParamWire; "rotation": ParamWire2; "scale": ParamWire; "size"?: (ParamWire | null) };
  export type LottieSamplingWire = { "fit": RasterFitWire };
  export type MediaEndBehaviorWire = ("error" | "hold" | "loop");
  export type MotionCueBindingWire = { "end": ExactRational; "enterDuration": ExactRational; "exitDuration": ExactRational; "start": ExactRational; "type": "source-range" };
  export type MotionPhaseOverridesWire = { "enterDuration": RequiredNullable_for_ExactRational; "exitDuration": RequiredNullable_for_ExactRational };
  export type NamedEasingWire = ("linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out");
  export type NamespacedKernelTypeWire = string;
  export type ParamWire = ({ "type": "constant"; "value": [number, number] } | { "extrapolation": ExtrapolationWire; "id": string; "interpolation": InterpolationWire; "keyframes": Array<KeyframeWire>; "type": "curve" });
  export type ParamWire2 = ({ "type": "constant"; "value": number } | { "extrapolation": ExtrapolationWire; "id": string; "interpolation": InterpolationWire; "keyframes": Array<KeyframeWire2>; "type": "curve" });
  export type ParamWire3 = ({ "type": "constant"; "value": [number, number, number, number] } | { "extrapolation": ExtrapolationWire; "id": string; "interpolation": InterpolationWire; "keyframes": Array<KeyframeWire3>; "type": "curve" });
  export type ParamWire4 = ({ "type": "constant"; "value": JsonValue } | { "extrapolation": ExtrapolationWire; "id": string; "interpolation": InterpolationWire; "keyframes": Array<KeyframeWire4>; "type": "curve" });
  export type RasterFitWire = ("contain" | "cover" | "fill" | "none");
  export type RasterSamplingWire = { "fit": RasterFitWire };
  export type RequiredNullable_for_CameraTrackWire = (CameraTrackWire | null);
  export type RequiredNullable_for_CaptionBehaviorWire = (CaptionBehaviorWire | null);
  export type RequiredNullable_for_CaptionShadowWire = (CaptionShadowWire | null);
  export type RequiredNullable_for_EasingWire = (EasingWire | null);
  export type RequiredNullable_for_ExactRational = (ExactRational | null);
  export type RequiredNullable_for_LayerMaskWire = (LayerMaskWire | null);
  export type RequiredNullable_for_TextRunStyleWire = (TextRunStyleWire | null);
  export type RequiredNullable_for_TextRunTimingWire = (TextRunTimingWire | null);
  export type RequiredNullable_for_double = (number | null);
  export type RequiredNullable_for_string = (string | null);
  export type ScrollAxisWire = ("horizontal" | "vertical");
  export type TextRunStyleWire = { "color": RequiredNullable_for_string; "fontSize": RequiredNullable_for_double };
  export type TextRunTimingWire = { "end": ExactRational; "start": ExactRational };
  export type TextRunWire = { "id": string; "style": RequiredNullable_for_TextRunStyleWire; "text": string; "timing": RequiredNullable_for_TextRunTimingWire };
  export type TimedAdjustmentWire = { "duration": ExactRational; "effect": AdjustmentEffectWire; "id": string; "start": ExactRational };
  export type TimelineDocumentWire = { "adjustments": Array<TimedAdjustmentWire>; "audio": AudioCompositionWire; "background": BackgroundWire; "camera": RequiredNullable_for_CameraTrackWire; "canvas": CanvasWire; "captions": CaptionCompositionWire; "metadata": Record<string, JsonValue>; "visual": VisualCompositionWire };
  export type TransitionKernelExtensionWire = { "parameters": Record<string, JsonValue>; "type": NamespacedKernelTypeWire };
  export type TransitionKernelWire = (CrossFadeTransitionKernelWire | TransitionKernelExtensionWire);
  export type VisualCompositionWire = { "tracks": Array<VisualTrackWire> };
  export type VisualFilterWire = { "id": string; "parameters": Record<string, JsonValue>; "type": NamespacedKernelTypeWire };
  export type VisualItemWire = ({ "duration": ExactRational; "id": string; "layer": VisualLayerWire; "source": VisualSourceWire; "type": "clip" } | { "duration": ExactRational; "id": string; "type": "gap" } | { "duration": ExactRational; "id": string; "kernel": TransitionKernelWire; "type": "transition" });
  export type VisualLayerWire = { "blend": BlendModeWire; "filters": Array<VisualFilterWire>; "mask": RequiredNullable_for_LayerMaskWire; "opacity": ParamWire2; "transform": LayerTransformWire };
  export type VisualSourceWire = ({ "endBehavior": MediaEndBehaviorWire; "gain"?: (ParamWire2 | null); "rate": ExactRational; "resource": string; "sampling": RasterSamplingWire; "sourceStart": ExactRational; "type": "video" } | { "resource": string; "sampling": RasterSamplingWire; "type": "image" } | { "endBehavior": MediaEndBehaviorWire; "rate": ExactRational; "resource": string; "sampling": LottieSamplingWire; "sourceStart": ExactRational; "type": "lottie" } | { "component": string; "cues": Record<string, MotionCueBindingWire>; "endBehavior": MediaEndBehaviorWire; "phases": MotionPhaseOverridesWire; "props": Record<string, ParamWire4>; "rate": ExactRational; "resources": Record<string, string>; "sourceDuration": ExactRational; "sourceStart": ExactRational; "type": "motion" } | { "color": string; "type": "solid" });
  export type VisualTrackWire = { "id": string; "items": Array<VisualItemWire> };
}
export type TimelineDocument = TimelineDocumentSchema.Root;

export namespace ResourceManifestSchema {
  export type Root = { "entries": Record<string, ResourceEntryWire> };
  export type AudioChannelLayoutWire = ("mono" | "stereo" | "surround51" | "surround71");
  export type AudioResourceDescriptorWire = { "audioStream": number; "channelLayout": AudioChannelLayoutWire; "duration": RationalTime; "presentationIndexDigest": ContentDigest; "sampleRate": number; "timeBase": ExactRational };
  export type ColorMatrixWire = ("identity" | "bt709" | "bt2020-ncl");
  export type ColorPrimariesWire = ("srgb" | "bt709" | "display-p3" | "bt2020");
  export type ColorTransferWire = ("srgb" | "bt709" | "pq" | "hlg");
  export type ContentDigest = string;
  export type ContinuousBoundarySamplingWire = "left-limit";
  export type ExactRational = string;
  export type FontResourceDescriptorWire = { "faceIndex": number; "variationAxes": Record<string, FontVariationAxisWire> };
  export type FontVariationAxisWire = { "default": number; "maximum": number; "minimum": number };
  export type ImageResourceDescriptorWire = { "color": MediaColorDescriptorWire; "height": number; "orientation": MediaOrientationWire; "width": number };
  export type LottieArtifactAbiWire = "valle.lottie/artifact@1";
  export type LottieResourceDescriptorWire = { "boundarySampling": ContinuousBoundarySamplingWire; "duration": RationalTime; "height": number; "timeBase": ExactRational; "width": number };
  export type MediaColorDescriptorWire = { "fullRange": boolean; "matrix": ColorMatrixWire; "primaries": ColorPrimariesWire; "transfer": ColorTransferWire };
  export type MediaOrientationWire = ("identity" | "rotate-90" | "rotate-180" | "rotate-270" | "flip-horizontal" | "flip-vertical");
  export type MotionArtifactAbiWire = "valle.motion/artifact@1";
  export type MotionArtifactDescriptorWire = { "boundarySampling": ContinuousBoundarySamplingWire; "readsDestination": boolean };
  export type RationalTime = string;
  export type RequiredNullable_for_uint32 = (number | null);
  export type ResourceEntryWire = ({ "descriptor": VideoResourceDescriptorWire; "digest": ContentDigest; "kind": "video" } | { "descriptor": AudioResourceDescriptorWire; "digest": ContentDigest; "kind": "audio" } | { "descriptor": ImageResourceDescriptorWire; "digest": ContentDigest; "kind": "image" } | { "abi": LottieArtifactAbiWire; "descriptor": LottieResourceDescriptorWire; "digest": ContentDigest; "kind": "lottie" } | { "descriptor": FontResourceDescriptorWire; "digest": ContentDigest; "kind": "font" } | { "abi": MotionArtifactAbiWire; "descriptor": MotionArtifactDescriptorWire; "digest": ContentDigest; "kind": "motion-artifact" } | { "abi": ShaderArtifactAbiWire; "descriptor": ShaderResourceDescriptorWire; "digest": ContentDigest; "kind": "shader" });
  export type ShaderArtifactAbiWire = "valle.shader/artifact@1";
  export type ShaderResourceDescriptorWire = { "controlsSchemaDigest": ContentDigest; "readsDestination": boolean };
  export type VideoResourceDescriptorWire = { "audioStream": RequiredNullable_for_uint32; "color": MediaColorDescriptorWire; "duration": RationalTime; "height": number; "orientation": MediaOrientationWire; "presentationIndexDigest": ContentDigest; "timeBase": ExactRational; "videoStream": number; "width": number };
}
export type ResourceManifest = ResourceManifestSchema.Root;
