//! Build-only JSON Schema export for workspace-internal render contracts.
//!
//! This module is intentionally feature-gated. Runtime consumers of
//! `valle-timeline` do not link either the generator or the corpus validator.

use std::{borrow::Cow, collections::BTreeMap};

use schemars::{JsonSchema, Schema, SchemaGenerator, generate::SchemaSettings, json_schema};
use serde_json::{Value as JsonValue, json};

use crate::internal::{
    ContentDigest,
    identity::RenderId,
    wire::{
        document::{NamespacedKernelTypeWire, TimelineDocumentEnvelopeWire},
        resource::ResourceManifestEnvelopeWire,
    },
};

pub use crate::schema::SCHEMARS_VERSION;
pub const JSON_SCHEMA_DRAFT: &str = "2020-12";
pub const SCHEMA_BUNDLE_FILE: &str = "timeline.internal.schema-bundle.json";
pub const TYPESCRIPT_FILE: &str = "timeline.internal.generated.ts";

const SHA256_PATTERN: &str = r"^sha256:[0-9a-f]{64}$";
const NAMESPACED_KERNEL_PATTERN: &str = r"^[^/\s]+/[^/\s]+$";

/// Makes an `Option<T>` nullable on the wire without making the containing
/// object property optional. This matches fields decoded through
/// `required_option`, where a missing key is rejected but explicit `null` is
/// canonical.
pub(crate) struct RequiredNullable<T>(std::marker::PhantomData<T>);

impl<T> JsonSchema for RequiredNullable<T>
where
    T: JsonSchema,
{
    fn schema_name() -> Cow<'static, str> {
        format!("RequiredNullable_for_{}", T::schema_name()).into()
    }

    fn schema_id() -> Cow<'static, str> {
        format!("{}::RequiredNullable<{}>", module_path!(), T::schema_id()).into()
    }

    fn json_schema(generator: &mut SchemaGenerator) -> Schema {
        generator.subschema_for::<Option<T>>()
    }
}

/// Generate the narrow set of canonical/storage schemas currently consumed by
/// the Web runtime. These are implementation artifacts, not public timeline
/// contracts.
pub fn generated_schemas() -> BTreeMap<&'static str, JsonValue> {
    BTreeMap::from([
        (
            "timeline-document.schema.json",
            root_schema::<TimelineDocumentEnvelopeWire>(),
        ),
        (
            "resource-manifest.schema.json",
            root_schema::<ResourceManifestEnvelopeWire>(),
        ),
    ])
}

/// Generate TypeScript for the canonical/storage implementation boundary.
pub fn generated_typescript() -> String {
    const ROOTS: [(&str, &str, &str); 2] = [
        (
            "timeline-document.schema.json",
            "TimelineDocumentSchema",
            "TimelineDocument",
        ),
        (
            "resource-manifest.schema.json",
            "ResourceManifestSchema",
            "ResourceManifest",
        ),
    ];

    typescript_from_schemas(&generated_schemas(), &ROOTS, "internal canonical/storage")
}

fn typescript_from_schemas(
    schemas: &BTreeMap<&'static str, JsonValue>,
    roots: &[(&str, &str, &str)],
    surface: &str,
) -> String {
    let mut output = format!(
        "// @generated by valle-timeline internal schema-gen; do not edit.\n\
         // Source: Rust wire DTOs -> schemars {} (Draft {}).\n\
         // Surface: {surface}.\n\
         // Runtime validation and canonicalization remain in Rust/WASM.\n\n\
         export type JsonValue = null | boolean | number | string | JsonValue[] | {{ [key: string]: JsonValue }};\n\n",
        SCHEMARS_VERSION, JSON_SCHEMA_DRAFT
    );

    for (schema_file, namespace, root_alias) in roots {
        let schema = schemas
            .get(*schema_file)
            .unwrap_or_else(|| panic!("missing generated schema {schema_file}"));
        output.push_str(&format!("export namespace {namespace} {{\n"));
        output.push_str(&format!(
            "  export type Root = {};\n",
            typescript_type(schema)
        ));
        if let Some(definitions) = schema.get("$defs").and_then(JsonValue::as_object) {
            for (name, definition) in definitions {
                output.push_str(&format!(
                    "  export type {} = {};\n",
                    typescript_identifier(name),
                    typescript_type(definition)
                ));
            }
        }
        output.push_str("}\n");
        output.push_str(&format!("export type {root_alias} = {namespace}.Root;\n\n"));
    }

    debug_assert!(output.ends_with("\n\n"));
    output.pop();
    output
}

/// Complete deterministic output set used by `schema-gen` and the zero-diff
/// test gate.
pub fn generated_artifacts() -> BTreeMap<&'static str, String> {
    BTreeMap::from([
        (SCHEMA_BUNDLE_FILE, schema_bundle_pretty()),
        (TYPESCRIPT_FILE, generated_typescript()),
    ])
}

/// Deterministic checked-in bundle. Generator/draft/contract mode are part of
/// the artifact so a toolchain change cannot silently rewrite schema output.
pub fn schema_bundle_pretty() -> String {
    let bundle = json!({
        "generator": generator_metadata("internal-canonical-storage"),
        "schemas": generated_schemas()
    });
    pretty_json(&bundle)
}

fn root_schema<T: JsonSchema>() -> JsonValue {
    let schema = SchemaSettings::draft2020_12()
        .for_deserialize()
        .into_generator()
        .into_root_schema_for::<T>();
    serde_json::to_value(schema).expect("generated schema serializes")
}

fn generator_metadata(mode: &'static str) -> JsonValue {
    json!({
        "crate": "schemars",
        "version": SCHEMARS_VERSION,
        "draft": JSON_SCHEMA_DRAFT,
        "mode": mode
    })
}

fn pretty_json(value: &JsonValue) -> String {
    let mut output = serde_json::to_string_pretty(value).expect("generated artifact serializes");
    output.push('\n');
    output
}

fn typescript_type(schema: &JsonValue) -> String {
    match schema {
        JsonValue::Bool(true) => return "JsonValue".to_owned(),
        JsonValue::Bool(false) => return "never".to_owned(),
        JsonValue::Object(_) => {}
        _ => return "JsonValue".to_owned(),
    }

    if let Some(reference) = schema.get("$ref").and_then(JsonValue::as_str) {
        let name = reference
            .strip_prefix("#/$defs/")
            .unwrap_or_else(|| panic!("unsupported TypeScript schema reference `{reference}`"));
        return typescript_identifier(&json_pointer_unescape(name));
    }
    if let Some(constant) = schema.get("const") {
        return typescript_literal(constant);
    }
    if let Some(values) = schema.get("enum").and_then(JsonValue::as_array) {
        return union_type(values.iter().map(typescript_literal));
    }
    for (keyword, union) in [("oneOf", true), ("anyOf", true), ("allOf", false)] {
        let Some(branches) = schema.get(keyword).and_then(JsonValue::as_array) else {
            continue;
        };
        let parent_closes_object = matches!(
            schema.get("unevaluatedProperties"),
            Some(JsonValue::Bool(false))
        );
        let branch_type = if union {
            union_type(branches.iter().map(|branch| {
                typescript_type(&typescript_branch_schema(branch, parent_closes_object))
            }))
        } else {
            intersection_type(branches.iter().map(|branch| {
                typescript_type(&typescript_branch_schema(branch, parent_closes_object))
            }))
        };

        // Schemars represents a flattened tagged enum as sibling object properties plus oneOf.
        // JSON Schema evaluates both halves and closes the combined object with
        // unevaluatedProperties=false. Preserve that intersection in TypeScript instead of
        // dropping the common fields (start/duration/transform) or widening every variant with
        // Record<string, JsonValue>.
        if schema.get("properties").is_some()
            || schema.get("additionalProperties").is_some()
            || schema.get("type").is_some()
        {
            let mut common = schema.clone();
            let common = common
                .as_object_mut()
                .expect("TypeScript schema is an object");
            common.remove("oneOf");
            common.remove("anyOf");
            common.remove("allOf");
            return intersection_type(
                [
                    typescript_type(&JsonValue::Object(common.clone())),
                    branch_type,
                ]
                .into_iter(),
            );
        }
        return branch_type;
    }

    match schema.get("type") {
        Some(JsonValue::String(kind)) => typescript_kind(kind, schema),
        Some(JsonValue::Array(kinds)) => union_type(kinds.iter().map(|kind| {
            kind.as_str()
                .map(|kind| typescript_kind(kind, schema))
                .unwrap_or_else(|| "JsonValue".to_owned())
        })),
        _ if schema.get("properties").is_some() || schema.get("additionalProperties").is_some() => {
            typescript_object(schema)
        }
        _ => "JsonValue".to_owned(),
    }
}

fn typescript_kind(kind: &str, schema: &JsonValue) -> String {
    match kind {
        "null" => "null".to_owned(),
        "boolean" => "boolean".to_owned(),
        "integer" | "number" => "number".to_owned(),
        "string" => "string".to_owned(),
        "array" => typescript_array(schema),
        "object" => typescript_object(schema),
        _ => "JsonValue".to_owned(),
    }
}

fn typescript_array(schema: &JsonValue) -> String {
    if let Some(items) = schema.get("prefixItems").and_then(JsonValue::as_array) {
        return format!(
            "[{}]",
            items
                .iter()
                .map(typescript_type)
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    let item = schema
        .get("items")
        .map(typescript_type)
        .unwrap_or_else(|| "JsonValue".to_owned());
    let fixed_length = schema
        .get("minItems")
        .and_then(JsonValue::as_u64)
        .zip(schema.get("maxItems").and_then(JsonValue::as_u64))
        .filter(|(min, max)| min == max && *min <= 32)
        .map(|(length, _)| length);
    if let Some(length) = fixed_length {
        return format!(
            "[{}]",
            std::iter::repeat_n(item, length as usize)
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    format!("Array<{item}>")
}

fn typescript_object(schema: &JsonValue) -> String {
    let properties = schema.get("properties").and_then(JsonValue::as_object);
    let required = schema
        .get("required")
        .and_then(JsonValue::as_array)
        .into_iter()
        .flatten()
        .filter_map(JsonValue::as_str)
        .collect::<std::collections::BTreeSet<_>>();

    let mut fields = Vec::new();
    if let Some(properties) = properties {
        for (name, property_schema) in properties {
            let optional = if required.contains(name.as_str()) {
                ""
            } else {
                "?"
            };
            fields.push(format!(
                "{}{}: {}",
                serde_json::to_string(name).expect("property name serializes"),
                optional,
                typescript_type(property_schema)
            ));
        }
    }

    let closed = matches!(
        schema.get("additionalProperties"),
        Some(JsonValue::Bool(false))
    ) || matches!(
        schema.get("unevaluatedProperties"),
        Some(JsonValue::Bool(false))
    );
    let additional = match schema.get("additionalProperties") {
        Some(JsonValue::Object(_)) => schema.get("additionalProperties").map(typescript_type),
        Some(JsonValue::Bool(false)) => None,
        _ => Some("JsonValue".to_owned()),
    };
    let shape = if fields.is_empty() {
        if closed {
            "Record<string, never>".to_owned()
        } else if let Some(additional) = &additional {
            format!("Record<string, {additional}>")
        } else {
            "Record<string, never>".to_owned()
        }
    } else {
        format!("{{ {} }}", fields.join("; "))
    };

    if fields.is_empty() || closed {
        shape
    } else if let Some(additional) = &additional {
        format!("({shape} & Record<string, {additional}>)")
    } else {
        shape
    }
}

fn typescript_branch_schema(schema: &JsonValue, close_object: bool) -> JsonValue {
    if !close_object {
        return schema.clone();
    }
    let mut schema = schema.clone();
    let Some(object) = schema.as_object_mut() else {
        return schema;
    };
    if object.get("type").and_then(JsonValue::as_str) == Some("object")
        || object.contains_key("properties")
    {
        object.insert("additionalProperties".to_owned(), JsonValue::Bool(false));
    }
    schema
}

fn union_type(types: impl Iterator<Item = String>) -> String {
    let mut unique = Vec::new();
    for kind in types {
        if !unique.contains(&kind) {
            unique.push(kind);
        }
    }
    match unique.len() {
        0 => "never".to_owned(),
        1 => unique.pop().expect("one union member"),
        _ => format!("({})", unique.join(" | ")),
    }
}

fn intersection_type(types: impl Iterator<Item = String>) -> String {
    let types = types.collect::<Vec<_>>();
    match types.len() {
        0 => "JsonValue".to_owned(),
        1 => types.into_iter().next().expect("one intersection member"),
        _ => format!("({})", types.join(" & ")),
    }
}

fn typescript_literal(value: &JsonValue) -> String {
    match value {
        JsonValue::Null => "null".to_owned(),
        JsonValue::Bool(value) => value.to_string(),
        JsonValue::Number(value) => value.to_string(),
        JsonValue::String(value) => {
            serde_json::to_string(value).expect("TypeScript string literal serializes")
        }
        _ => "JsonValue".to_owned(),
    }
}

fn json_pointer_unescape(value: &str) -> String {
    value.replace("~1", "/").replace("~0", "~")
}

fn typescript_identifier(value: &str) -> String {
    let mut output = String::new();
    for (index, character) in value.chars().enumerate() {
        let valid = character == '_' || character == '$' || character.is_ascii_alphanumeric();
        if index == 0 && character.is_ascii_digit() {
            output.push('_');
        }
        output.push(if valid { character } else { '_' });
    }
    if output.is_empty() {
        output.push('_');
    }
    output
}

macro_rules! string_wire_schema {
    ($type:ty, $name:literal, $pattern:expr) => {
        impl JsonSchema for $type {
            fn schema_name() -> Cow<'static, str> {
                $name.into()
            }

            fn json_schema(_: &mut SchemaGenerator) -> Schema {
                json_schema!({ "type": "string", "pattern": $pattern })
            }
        }
    };
}

string_wire_schema!(RenderId, "RenderId", SHA256_PATTERN);
string_wire_schema!(ContentDigest, "ContentDigest", SHA256_PATTERN);
string_wire_schema!(
    NamespacedKernelTypeWire,
    "NamespacedKernelTypeWire",
    NAMESPACED_KERNEL_PATTERN
);
