use anyhow::{Context, Result, bail};
use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

mod notices;
mod package;

const MARKER: &str = ".valle-distribution";
const USAGE: &str = "Usage: cargo xtask build [--release]\n       cargo xtask package [--target TRIPLE] [--min-macos VERSION]\n       cargo xtask verify-package BINARY";

fn main() -> Result<()> {
    let args: Vec<_> = std::env::args().skip(1).collect();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    if args.first().is_some_and(|arg| arg == "package") {
        return package::package(root, &args[1..]);
    }
    if let [command, binary] = args.as_slice()
        && command == "verify-package"
    {
        return package::verify(Path::new(binary));
    }
    let release = match args
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>()
        .as_slice()
    {
        ["build"] => false,
        ["build", "--release"] => true,
        [] | ["--help" | "-h"] | ["build", "--help" | "-h"] => {
            println!("{USAGE}");
            return Ok(());
        }
        _ => bail!("{USAGE}"),
    };
    build_with_environment(root, release, &std::collections::BTreeMap::new())
}

fn build_with_environment(
    root: &Path,
    release: bool,
    environment: &std::collections::BTreeMap<String, String>,
) -> Result<()> {
    let output = root.join("dist");
    check_output(&output)?;
    run(Command::new("bun")
        .args(["install", "--frozen-lockfile"])
        .envs(environment)
        .current_dir(root.join("web")))?;
    run(Command::new("bun")
        .args(["run", "build"])
        .envs(environment)
        .current_dir(root.join("web")))?;
    // The CLI build embeds these inputs; the resulting executable is the whole distribution.
    let notices = root.join("target/distribution-notices.txt");
    notices::generate(root, &notices, release, environment)?;
    let mut environment = environment.clone();
    environment.insert(
        "VALLE_EMBED_WEB_DIR".into(),
        root.join("web/dist").display().to_string(),
    );
    environment.insert("VALLE_EMBED_NOTICES".into(), notices.display().to_string());
    let binary = build_cli(root, release, &environment)?;
    assemble(&output, &binary)?;
    println!("Built {}", output.display());
    Ok(())
}

fn run(command: &mut Command) -> Result<()> {
    let status = command
        .status()
        .with_context(|| format!("cannot start {command:?}"))?;
    if !status.success() {
        bail!("{command:?} failed with {status}");
    }
    Ok(())
}

fn build_cli(
    root: &Path,
    release: bool,
    environment: &std::collections::BTreeMap<String, String>,
) -> Result<PathBuf> {
    let mut command = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    command.envs(environment).current_dir(root).args([
        "build",
        "--locked",
        "-p",
        "valle-cli",
        "--message-format=json-render-diagnostics",
        "--features",
        "embedded-runtime",
    ]);
    if release {
        command.arg("--release");
    }
    // Read Cargo's artifact path instead of assuming a target directory or host triple.
    let output = command
        .stderr(Stdio::inherit())
        .output()
        .context("cannot start Cargo")?;
    if !output.status.success() {
        bail!("CLI build failed with {}", output.status);
    }
    for line in output.stdout.split(|byte| *byte == b'\n') {
        let Ok(message) = serde_json::from_slice::<serde_json::Value>(line) else {
            continue;
        };
        if message["reason"] == "compiler-artifact"
            && message["target"]["name"] == "valle"
            && let Some(path) = message["executable"].as_str()
        {
            return Ok(PathBuf::from(path));
        }
    }
    bail!("Cargo did not report the valle executable")
}

fn check_output(output: &Path) -> Result<()> {
    if output.symlink_metadata().is_ok() && !output.join(MARKER).is_file() {
        bail!(
            "{} is not a generated Valle distribution; move it aside before building",
            output.display()
        );
    }
    Ok(())
}

fn assemble(output: &Path, binary: &Path) -> Result<()> {
    check_output(output)?;
    let staging = tempfile::Builder::new()
        .prefix(".dist-build-")
        .tempdir_in(output.parent().context("missing output parent")?)?;
    let next = staging.path().join("next");
    let previous = staging.path().join("previous");
    fs::create_dir_all(next.join("bin"))?;
    // fs::copy preserves executable permissions.
    fs::copy(
        binary,
        next.join("bin")
            .join(binary.file_name().context("missing executable name")?),
    )?;
    fs::write(next.join(MARKER), "Generated by cargo xtask build\n")?;
    if output.exists() {
        fs::rename(output, &previous)?;
    }
    if let Err(error) = fs::rename(&next, output) {
        if previous.exists()
            && let Err(restore_error) = fs::rename(&previous, output)
        {
            let retained = staging.keep();
            bail!(
                "cannot install distribution: {error}; cannot restore previous distribution: {restore_error}; backup retained in {}",
                retained.display()
            );
        }
        return Err(error.into());
    }
    staging.close()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refuses_unmarked_output() -> Result<()> {
        let dir = tempfile::tempdir()?;
        fs::write(dir.path().join("user-file"), "keep")?;
        assert!(check_output(dir.path()).is_err());
        assert_eq!(fs::read_to_string(dir.path().join("user-file"))?, "keep");
        Ok(())
    }

    #[test]
    fn replaces_distribution_and_preserves_executable() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let binary = dir.path().join("valle");
        fs::write(&binary, "binary")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&binary, fs::Permissions::from_mode(0o755))?;
        }
        let output = dir.path().join("dist");
        assemble(&output, &binary)?;
        fs::write(output.join("obsolete"), "old")?;
        assemble(&output, &binary)?;
        assert!(!output.join("obsolete").exists());
        assert!(!output.join("web").exists());
        assert_eq!(fs::read_to_string(output.join("bin/valle"))?, "binary");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(output.join("bin/valle"))?.permissions().mode() & 0o777,
                0o755
            );
        }
        Ok(())
    }

    #[test]
    fn failed_copy_keeps_previous_distribution() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let output = dir.path().join("dist");
        fs::create_dir(&output)?;
        fs::write(output.join(MARKER), "old")?;
        assert!(assemble(&output, &dir.path().join("missing")).is_err());
        assert_eq!(fs::read_to_string(output.join(MARKER))?, "old");
        assert_eq!(fs::read_dir(dir.path())?.count(), 1);
        Ok(())
    }
}

#[cfg(test)]
mod contract_tests {
    use super::*;

    #[test]
    fn commands_report_start_and_exit_failures() {
        #[cfg(unix)]
        {
            run(Command::new("/usr/bin/true").arg("unused")).unwrap();
            assert!(run(Command::new("/usr/bin/false").arg("unused")).is_err());
        }
        #[cfg(windows)]
        {
            run(Command::new("cmd.exe").args(["/C", "exit", "0"])).unwrap();
            assert!(run(Command::new("cmd.exe").args(["/C", "exit", "1"])).is_err());
        }
        assert!(run(&mut Command::new("/nonexistent/valle-test-command")).is_err());
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir(dir.path().join("dist")).unwrap();
        fs::write(dir.path().join("dist/user-file"), "keep").unwrap();
        assert!(build_with_environment(dir.path(), false, &Default::default()).is_err());
        assert_eq!(
            fs::read_to_string(dir.path().join("dist/user-file")).unwrap(),
            "keep"
        );
    }

    #[test]
    #[ignore = "runs the actual locked native CLI build with embedded runtime inputs"]
    fn locked_cli_build_returns_the_cargo_reported_executable() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let target = std::env::var("CARGO_LLVM_COV_TARGET_DIR")
            .unwrap_or_else(|_| root.join("target").display().to_string());
        let environment =
            std::collections::BTreeMap::from([("CARGO_TARGET_DIR".to_owned(), target.clone())]);
        let binary = build_cli(root, false, &environment).unwrap();
        assert!(binary.starts_with(&target));
        assert!(binary.is_file());
        assert_eq!(binary.file_name().unwrap(), "valle");
        assert!(
            package::capture(Command::new(binary).arg("--version"))
                .unwrap()
                .starts_with("valle ")
        );
    }

    #[test]
    fn actual_license_collection_includes_native_web_and_font_provenance() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let temp = tempfile::tempdir().unwrap();
        let output = temp.path().join("notices.txt");
        notices::generate(root, &output, false, &Default::default()).unwrap();
        let text = fs::read_to_string(output).unwrap();
        assert!(!text.contains("===== Web: valle-engine "));
        for required in [
            "Valle base revision:",
            "Rust: valle-asr 0.1.0",
            "Rust: valle-tts 0.1.0",
            "vendor/qwentts/LICENSE",
            "vendor/ggml/LICENSE",
            "Apache License",
            "cssparser",
            "https://static.crates.io/",
            "GL-Transitions-MIT.txt",
            "OFL",
            "CanvasKit",
        ] {
            assert!(text.contains(required), "{required}");
        }
    }
}
