use anyhow::{Context, Result, bail};
use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

const MARKER: &str = ".valle-distribution";
const USAGE: &str = "Usage: cargo xtask build [--release]";

fn main() -> Result<()> {
    let args: Vec<_> = std::env::args().skip(1).collect();
    let release = match args
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>()
        .as_slice()
    {
        ["build"] => false,
        ["build", "--release"] => true,
        [] | ["--help" | "-h"] | ["build", "--help" | "-h"] => {
            println!("{USAGE}");
            return Ok(());
        }
        _ => bail!("{USAGE}"),
    };
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
    let output = root.join("dist");
    check_output(&output)?;
    run(Command::new("bun")
        .args(["install", "--frozen-lockfile"])
        .current_dir(root.join("web")))?;
    run(Command::new("bun")
        .args(["run", "build"])
        .current_dir(root.join("web")))?;
    let binary = build_cli(root, release)?;
    assemble(&output, &binary, &root.join("web/dist"))?;
    println!("Built {}", output.display());
    Ok(())
}

fn run(command: &mut Command) -> Result<()> {
    let status = command
        .status()
        .with_context(|| format!("cannot start {command:?}"))?;
    if !status.success() {
        bail!("{command:?} failed with {status}");
    }
    Ok(())
}

fn build_cli(root: &Path, release: bool) -> Result<PathBuf> {
    let mut command = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    command.current_dir(root).args([
        "build",
        "--locked",
        "-p",
        "valle-cli",
        "--message-format=json-render-diagnostics",
    ]);
    if release {
        command.arg("--release");
    }
    // Read Cargo's artifact path instead of assuming a target directory or host triple.
    let output = command
        .stderr(Stdio::inherit())
        .output()
        .context("cannot start Cargo")?;
    if !output.status.success() {
        bail!("CLI build failed with {}", output.status);
    }
    for line in output.stdout.split(|byte| *byte == b'\n') {
        let Ok(message) = serde_json::from_slice::<serde_json::Value>(line) else {
            continue;
        };
        if message["reason"] == "compiler-artifact"
            && message["target"]["name"] == "valle"
            && let Some(path) = message["executable"].as_str()
        {
            return Ok(PathBuf::from(path));
        }
    }
    bail!("Cargo did not report the valle executable")
}

fn check_output(output: &Path) -> Result<()> {
    if output.symlink_metadata().is_ok() && !output.join(MARKER).is_file() {
        bail!(
            "{} is not a generated Valle distribution; move it aside before building",
            output.display()
        );
    }
    Ok(())
}

fn copy_tree(source: &Path, destination: &Path) -> Result<()> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let target = destination.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_tree(&entry.path(), &target)?;
        } else {
            fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

fn assemble(output: &Path, binary: &Path, web: &Path) -> Result<()> {
    check_output(output)?;
    let staging = tempfile::Builder::new()
        .prefix(".dist-build-")
        .tempdir_in(output.parent().context("missing output parent")?)?;
    let next = staging.path().join("next");
    let previous = staging.path().join("previous");
    fs::create_dir_all(next.join("bin"))?;
    // fs::copy preserves executable permissions.
    fs::copy(
        binary,
        next.join("bin")
            .join(binary.file_name().context("missing executable name")?),
    )?;
    copy_tree(web, &next.join("share/valle/web"))?;
    fs::write(next.join(MARKER), "Generated by cargo xtask build\n")?;
    if output.exists() {
        fs::rename(output, &previous)?;
    }
    if let Err(error) = fs::rename(&next, output) {
        if previous.exists()
            && let Err(restore_error) = fs::rename(&previous, output)
        {
            let retained = staging.keep();
            bail!(
                "cannot install distribution: {error}; cannot restore previous distribution: {restore_error}; backup retained in {}",
                retained.display()
            );
        }
        return Err(error.into());
    }
    staging.close()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refuses_unmarked_output() -> Result<()> {
        let dir = tempfile::tempdir()?;
        fs::write(dir.path().join("user-file"), "keep")?;
        assert!(check_output(dir.path()).is_err());
        assert_eq!(fs::read_to_string(dir.path().join("user-file"))?, "keep");
        Ok(())
    }

    #[test]
    fn replaces_distribution_and_preserves_executable() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let binary = dir.path().join("valle");
        fs::write(&binary, "binary")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&binary, fs::Permissions::from_mode(0o755))?;
        }
        let web = dir.path().join("web");
        fs::create_dir_all(web.join("studio"))?;
        fs::write(web.join("studio/index.html"), "studio")?;
        let output = dir.path().join("dist");
        assemble(&output, &binary, &web)?;
        fs::write(output.join("obsolete"), "old")?;
        assemble(&output, &binary, &web)?;
        assert!(!output.join("obsolete").exists());
        assert_eq!(
            fs::read_to_string(output.join("share/valle/web/studio/index.html"))?,
            "studio"
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(output.join("bin/valle"))?.permissions().mode() & 0o777,
                0o755
            );
        }
        Ok(())
    }

    #[test]
    fn failed_copy_keeps_previous_distribution() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let output = dir.path().join("dist");
        fs::create_dir(&output)?;
        fs::write(output.join(MARKER), "old")?;
        assert!(
            assemble(
                &output,
                &dir.path().join("missing"),
                &dir.path().join("web")
            )
            .is_err()
        );
        assert_eq!(fs::read_to_string(output.join(MARKER))?, "old");
        assert_eq!(fs::read_dir(dir.path())?.count(), 1);
        Ok(())
    }
}
