//! One verified executable and its checksum. CI handles distribution archives.
mod verify;
use anyhow::{Context, Result, bail, ensure};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Read,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};
pub use verify::verify;

pub fn package(root: &Path, args: &[String]) -> Result<()> {
    host_platform()?;
    let ceiling = match args {
        [] => None,
        [flag, value] if flag == "--min-macos" => {
            ensure!(cfg!(target_os = "macos"), "--min-macos requires macOS");
            Some(version(value)?)
        }
        _ => bail!("{}", super::USAGE),
    };
    let output = root.join("target/package");
    super::check_output(&output)?;
    let mut environment = BTreeMap::new();
    if let Some(minimum) = ceiling {
        environment.insert(
            "MACOSX_DEPLOYMENT_TARGET".to_owned(),
            display_version(minimum),
        );
    }
    super::build_with_environment(root, true, &environment)?;
    let staging = tempfile::Builder::new()
        .prefix("valle-package-")
        .tempdir_in(root.join("target"))?;
    let next = staging.path().join("next");
    fs::create_dir(&next)?;
    let name = executable_name();
    let binary = next.join(&name);
    fs::copy(root.join("dist/bin").join(executable_name()), &binary)?;
    if let Some(ceiling) = ceiling {
        let minimum = version(&inspect(&binary)?.minimum)?;
        ensure!(
            minimum <= ceiling,
            "binary requires macOS {}, exceeds requested {}",
            display_version(minimum),
            display_version(ceiling)
        );
    }
    if cfg!(target_os = "macos") {
        prepare_executable(&binary)?;
    }
    verify(&binary)?;
    fs::write(
        next.join("SHA256SUMS"),
        format!("{}  {name}\n", hash_file(&binary)?),
    )?;
    fs::write(
        next.join(super::MARKER),
        "Generated by cargo xtask package\n",
    )?;
    super::check_output(&output)?;
    let previous = staging.path().join("previous");
    if output.exists() {
        fs::rename(&output, &previous)?;
    }
    if let Err(error) = fs::rename(&next, &output) {
        if previous.exists()
            && let Err(restore) = fs::rename(&previous, &output)
        {
            let retained = staging.keep();
            bail!(
                "package install failed: {error}; restore failed: {restore}; backup retained at {}",
                retained.display()
            );
        }
        return Err(error.into());
    }
    println!("Packaged {}", output.join(name).display());
    if cfg!(target_os = "macos") {
        println!("macOS executable is ad-hoc signed, not notarized");
    }
    Ok(())
}

fn host_platform() -> Result<&'static str> {
    ensure!(
        !cfg!(windows) || cfg!(target_env = "msvc"),
        "Windows packaging requires the MSVC toolchain"
    );
    platform(std::env::consts::OS, std::env::consts::ARCH)
}

fn platform(os: &str, arch: &str) -> Result<&'static str> {
    match (os, arch) {
        ("macos", "aarch64") => Ok("darwin-arm64"),
        ("linux", "x86_64") => Ok("linux-x86_64"),
        ("windows", "x86_64") => Ok("windows-x86_64"),
        _ => bail!(
            "unsupported package host: {os}/{arch}; use macOS arm64, Linux x86_64 or Windows x86_64 MSVC"
        ),
    }
}

fn executable_name() -> String {
    format!("valle{}", std::env::consts::EXE_SUFFIX)
}

// Git for Windows also ships Unix tools. Use native Windows tools explicitly.
fn system_tool(name: &str) -> PathBuf {
    #[cfg(windows)]
    if let Some(root) = std::env::var_os("SystemRoot") {
        return PathBuf::from(root)
            .join("System32")
            .join(format!("{name}.exe"));
    }
    PathBuf::from(name)
}

pub(crate) fn capture(command: &mut Command) -> Result<String> {
    let output = command
        .stderr(Stdio::inherit())
        .output()
        .with_context(|| format!("cannot start {command:?}"))?;
    ensure!(
        output.status.success(),
        "{command:?} failed with {}",
        output.status
    );
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

pub(crate) fn hash_file(path: &Path) -> Result<String> {
    let mut input = fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buf = [0; 65536];
    loop {
        let n = input.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(hex::encode(hasher.finalize()))
}
pub(crate) fn version(value: &str) -> Result<[u32; 3]> {
    let parts = value
        .split('.')
        .map(str::parse::<u32>)
        .collect::<std::result::Result<Vec<_>, _>>()?;
    ensure!(
        !parts.is_empty() && parts.len() <= 3,
        "invalid macOS version: {value}"
    );
    let mut result = [0; 3];
    result[..parts.len()].copy_from_slice(&parts);
    Ok(result)
}
fn display_version(value: [u32; 3]) -> String {
    if value[2] == 0 {
        format!("{}.{}", value[0], value[1])
    } else {
        format!("{}.{}.{}", value[0], value[1], value[2])
    }
}
fn system_library(value: &str) -> bool {
    value.starts_with("/usr/lib/") || value.starts_with("/System/Library/")
}

#[derive(Debug)]
struct MachO {
    dependencies: Vec<String>,
    rpaths: Vec<String>,
    minimum: String,
}
fn inspect(path: &Path) -> Result<MachO> {
    let arch = capture(Command::new("/usr/bin/lipo").arg("-archs").arg(path))?;
    ensure!(
        arch == "arm64",
        "{} is {arch}, expected arm64",
        path.display()
    );
    let loads = capture(Command::new("/usr/bin/otool").arg("-l").arg(path))?;
    parse_loads(&loads).with_context(|| format!("reading Mach-O {}", path.display()))
}
fn parse_loads(text: &str) -> Result<MachO> {
    let mut result = MachO {
        dependencies: Vec::new(),
        rpaths: Vec::new(),
        minimum: String::new(),
    };
    let mut command = "";
    for line in text.lines().map(str::trim) {
        if let Some(value) = line.strip_prefix("cmd ") {
            command = value;
        }
        if matches!(
            command,
            "LC_LOAD_DYLIB" | "LC_LOAD_WEAK_DYLIB" | "LC_REEXPORT_DYLIB" | "LC_LOAD_UPWARD_DYLIB"
        ) {
            if let Some(value) = line
                .strip_prefix("name ")
                .and_then(|v| v.rsplit_once(" (offset ").map(|p| p.0))
            {
                result.dependencies.push(value.to_owned());
            }
        } else if command == "LC_RPATH" {
            if let Some(value) = line
                .strip_prefix("path ")
                .and_then(|v| v.rsplit_once(" (offset ").map(|p| p.0))
            {
                result.rpaths.push(value.to_owned());
            }
        } else if command == "LC_BUILD_VERSION" {
            if let Some(value) = line.strip_prefix("minos ") {
                result.minimum = value.to_owned();
            }
        } else if command == "LC_VERSION_MIN_MACOSX"
            && let Some(value) = line.strip_prefix("version ")
        {
            result.minimum = value.to_owned();
        }
    }
    version(&result.minimum)?;
    Ok(result)
}
fn prepare_executable(path: &Path) -> Result<()> {
    let info = inspect(path)?;
    for dependency in &info.dependencies {
        ensure!(
            system_library(dependency),
            "unexpected startup dependency: {dependency}; FFmpeg must be runtime-loaded and user-supplied"
        );
    }
    for rpath in &info.rpaths {
        super::run(
            Command::new("/usr/bin/install_name_tool")
                .args(["-delete_rpath", rpath])
                .arg(path),
        )?;
    }
    super::run(
        Command::new("/usr/bin/codesign")
            .args(["--force", "--sign", "-"])
            .arg(path),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn supports_only_the_published_platforms() -> Result<()> {
        assert_eq!(platform("macos", "aarch64")?, "darwin-arm64");
        assert_eq!(platform("linux", "x86_64")?, "linux-x86_64");
        assert_eq!(platform("windows", "x86_64")?, "windows-x86_64");
        assert!(platform("linux", "aarch64").is_err());
        assert!(platform("windows", "x86").is_err());
        Ok(())
    }
    #[test]
    fn reads_weak_edges_paths_with_spaces_and_ignores_install_id() -> Result<()> {
        let object = parse_loads(
            "cmd LC_ID_DYLIB\nname @rpath/self.dylib (offset 24)\ncmd LC_LOAD_WEAK_DYLIB\nname /path with spaces/lib.dylib (offset 24)\ncmd LC_RPATH\npath @loader_path/../lib (offset 12)\ncmd LC_BUILD_VERSION\nminos 14.2\n",
        )?;
        assert_eq!(object.dependencies, ["/path with spaces/lib.dylib"]);
        assert_eq!(object.rpaths, ["@loader_path/../lib"]);
        assert_eq!(version(&object.minimum)?, [14, 2, 0]);
        Ok(())
    }
    #[test]
    fn validates_macos_versions() -> Result<()> {
        assert!(version("15.10")? > version("15.9")?);
        assert!(version("15.0.0.1").is_err());
        Ok(())
    }
}
