//! One verified executable and its checksum. CI handles distribution archives.
mod verify;
use anyhow::{Context, Result, bail, ensure};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Read,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};
pub use verify::verify;

pub fn package(root: &Path, args: &[String]) -> Result<()> {
    let host = host_platform()?;
    let (target, ceiling) = package_options(args)?;
    let selected = target.map(target_platform).transpose()?.unwrap_or(host);
    ensure!(
        selected == host || (cfg!(target_os = "macos") && selected.starts_with("darwin-")),
        "cross-compilation is supported only between macOS arm64 and x86_64"
    );
    ensure!(
        ceiling.is_none() || cfg!(target_os = "macos"),
        "--min-macos requires macOS"
    );
    let output = root.join("target/package");
    super::check_output(&output)?;
    let mut environment = BTreeMap::new();
    if let Some(target) = target {
        environment.insert("CARGO_BUILD_TARGET".to_owned(), target.to_owned());
    }
    if let Some(minimum) = ceiling {
        environment.insert(
            "MACOSX_DEPLOYMENT_TARGET".to_owned(),
            display_version(minimum),
        );
    }
    super::build_with_environment(root, true, &environment)?;
    let staging = tempfile::Builder::new()
        .prefix("valle-package-")
        .tempdir_in(root.join("target"))?;
    let next = staging.path().join("next");
    fs::create_dir(&next)?;
    let name = executable_name();
    let binary = next.join(&name);
    fs::copy(root.join("dist/bin").join(executable_name()), &binary)?;
    if cfg!(target_os = "macos") {
        let expected = if selected == "darwin-arm64" {
            "arm64"
        } else {
            "x86_64"
        };
        ensure!(
            inspect(&binary)?.arch == expected,
            "binary does not match requested platform {selected}"
        );
    }
    if let Some(ceiling) = ceiling {
        let minimum = version(&inspect(&binary)?.minimum)?;
        ensure!(
            minimum <= ceiling,
            "binary requires macOS {}, exceeds requested {}",
            display_version(minimum),
            display_version(ceiling)
        );
    }
    if cfg!(target_os = "macos") {
        prepare_executable(&binary)?;
    }
    verify(&binary)?;
    fs::write(
        next.join("SHA256SUMS"),
        format!("{}  {name}\n", hash_file(&binary)?),
    )?;
    fs::write(
        next.join(super::MARKER),
        "Generated by cargo xtask package\n",
    )?;
    super::check_output(&output)?;
    let previous = staging.path().join("previous");
    if output.exists() {
        fs::rename(&output, &previous)?;
    }
    if let Err(error) = fs::rename(&next, &output) {
        if previous.exists()
            && let Err(restore) = fs::rename(&previous, &output)
        {
            let retained = staging.keep();
            bail!(
                "package install failed: {error}; restore failed: {restore}; backup retained at {}",
                retained.display()
            );
        }
        return Err(error.into());
    }
    println!("Packaged {}", output.join(name).display());
    if cfg!(target_os = "macos") {
        println!("macOS executable is ad-hoc signed, not notarized");
    }
    Ok(())
}

fn package_options(args: &[String]) -> Result<(Option<&str>, Option<[u32; 3]>)> {
    let mut target = None;
    let mut minimum = None;
    let mut args = args.iter();
    while let Some(flag) = args.next() {
        let value = args.next().context(super::USAGE)?;
        match flag.as_str() {
            "--target" if target.is_none() => {
                target_platform(value)?;
                target = Some(value.as_str());
            }
            "--min-macos" if minimum.is_none() => minimum = Some(version(value)?),
            _ => bail!("{}", super::USAGE),
        }
    }
    Ok((target, minimum))
}

fn target_platform(target: &str) -> Result<&'static str> {
    match target {
        "aarch64-apple-darwin" => platform("macos", "aarch64"),
        "x86_64-apple-darwin" => platform("macos", "x86_64"),
        "aarch64-unknown-linux-gnu" => platform("linux", "aarch64"),
        "x86_64-unknown-linux-gnu" => platform("linux", "x86_64"),
        "aarch64-pc-windows-msvc" => platform("windows", "aarch64"),
        "x86_64-pc-windows-msvc" => platform("windows", "x86_64"),
        _ => bail!("unsupported package target: {target}"),
    }
}

fn host_platform() -> Result<&'static str> {
    ensure!(
        !cfg!(windows) || cfg!(target_env = "msvc"),
        "Windows packaging requires the MSVC toolchain"
    );
    platform(std::env::consts::OS, std::env::consts::ARCH)
}

fn platform(os: &str, arch: &str) -> Result<&'static str> {
    match (os, arch) {
        ("macos", "aarch64") => Ok("darwin-arm64"),
        ("macos", "x86_64") => Ok("darwin-x86_64"),
        ("linux", "x86_64") => Ok("linux-x86_64"),
        ("linux", "aarch64") => Ok("linux-arm64"),
        ("windows", "x86_64") => Ok("windows-x86_64"),
        ("windows", "aarch64") => Ok("windows-arm64"),
        _ => bail!(
            "unsupported package host: {os}/{arch}; use macOS, Linux GNU or Windows MSVC on arm64 or x86_64"
        ),
    }
}

fn executable_name() -> String {
    format!("valle{}", std::env::consts::EXE_SUFFIX)
}

// Git for Windows also ships Unix tools. Use native Windows tools explicitly.
fn system_tool(name: &str) -> PathBuf {
    #[cfg(windows)]
    if let Some(root) = std::env::var_os("SystemRoot") {
        return PathBuf::from(root)
            .join("System32")
            .join(format!("{name}.exe"));
    }
    PathBuf::from(name)
}

pub(crate) fn capture(command: &mut Command) -> Result<String> {
    let output = command
        .stderr(Stdio::inherit())
        .output()
        .with_context(|| format!("cannot start {command:?}"))?;
    ensure!(
        output.status.success(),
        "{command:?} failed with {}",
        output.status
    );
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

pub(crate) fn hash_file(path: &Path) -> Result<String> {
    let mut input = fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buf = [0; 65536];
    loop {
        let n = input.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(hex::encode(hasher.finalize()))
}
pub(crate) fn version(value: &str) -> Result<[u32; 3]> {
    let parts = value
        .split('.')
        .map(str::parse::<u32>)
        .collect::<std::result::Result<Vec<_>, _>>()?;
    ensure!(
        !parts.is_empty() && parts.len() <= 3,
        "invalid macOS version: {value}"
    );
    let mut result = [0; 3];
    result[..parts.len()].copy_from_slice(&parts);
    Ok(result)
}
fn display_version(value: [u32; 3]) -> String {
    if value[2] == 0 {
        format!("{}.{}", value[0], value[1])
    } else {
        format!("{}.{}.{}", value[0], value[1], value[2])
    }
}
fn system_library(value: &str) -> bool {
    value.starts_with("/usr/lib/") || value.starts_with("/System/Library/")
}

#[derive(Debug)]
struct MachO {
    arch: String,
    dependencies: Vec<String>,
    rpaths: Vec<String>,
    minimum: String,
}
fn inspect(path: &Path) -> Result<MachO> {
    let arch = capture(Command::new("/usr/bin/lipo").arg("-archs").arg(path))?;
    ensure!(
        matches!(arch.as_str(), "arm64" | "x86_64"),
        "{} has unsupported architecture {arch}",
        path.display()
    );
    let loads = capture(Command::new("/usr/bin/otool").arg("-l").arg(path))?;
    let mut info =
        parse_loads(&loads).with_context(|| format!("reading Mach-O {}", path.display()))?;
    info.arch = arch;
    Ok(info)
}
fn parse_loads(text: &str) -> Result<MachO> {
    let mut result = MachO {
        arch: String::new(),
        dependencies: Vec::new(),
        rpaths: Vec::new(),
        minimum: String::new(),
    };
    let mut command = "";
    for line in text.lines().map(str::trim) {
        if let Some(value) = line.strip_prefix("cmd ") {
            command = value;
        }
        if matches!(
            command,
            "LC_LOAD_DYLIB" | "LC_LOAD_WEAK_DYLIB" | "LC_REEXPORT_DYLIB" | "LC_LOAD_UPWARD_DYLIB"
        ) {
            if let Some(value) = line
                .strip_prefix("name ")
                .and_then(|v| v.rsplit_once(" (offset ").map(|p| p.0))
            {
                result.dependencies.push(value.to_owned());
            }
        } else if command == "LC_RPATH" {
            if let Some(value) = line
                .strip_prefix("path ")
                .and_then(|v| v.rsplit_once(" (offset ").map(|p| p.0))
            {
                result.rpaths.push(value.to_owned());
            }
        } else if command == "LC_BUILD_VERSION" {
            if let Some(value) = line.strip_prefix("minos ") {
                result.minimum = value.to_owned();
            }
        } else if command == "LC_VERSION_MIN_MACOSX"
            && let Some(value) = line.strip_prefix("version ")
        {
            result.minimum = value.to_owned();
        }
    }
    version(&result.minimum)?;
    Ok(result)
}
fn prepare_executable(path: &Path) -> Result<()> {
    let info = inspect(path)?;
    for dependency in &info.dependencies {
        ensure!(
            system_library(dependency),
            "unexpected startup dependency: {dependency}; FFmpeg must be runtime-loaded and user-supplied"
        );
    }
    for rpath in &info.rpaths {
        super::run(
            Command::new("/usr/bin/install_name_tool")
                .args(["-delete_rpath", rpath])
                .arg(path),
        )?;
    }
    super::run(
        Command::new("/usr/bin/codesign")
            .args(["--force", "--sign", "-"])
            .arg(path),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn supports_only_the_published_platforms() -> Result<()> {
        assert_eq!(platform("macos", "aarch64")?, "darwin-arm64");
        assert_eq!(platform("linux", "x86_64")?, "linux-x86_64");
        assert_eq!(platform("windows", "x86_64")?, "windows-x86_64");
        assert_eq!(platform("macos", "x86_64")?, "darwin-x86_64");
        assert_eq!(platform("linux", "aarch64")?, "linux-arm64");
        assert_eq!(platform("windows", "aarch64")?, "windows-arm64");
        assert!(platform("windows", "x86").is_err());
        Ok(())
    }
    #[test]
    fn validates_cross_package_arguments_before_building() -> Result<()> {
        let args = ["--target", "x86_64-apple-darwin", "--min-macos", "15.0"].map(str::to_owned);
        assert_eq!(
            package_options(&args)?,
            (Some("x86_64-apple-darwin"), Some([15, 0, 0]))
        );
        for args in [
            vec!["--target"],
            vec!["--target", "wasm32-unknown-unknown"],
            vec![
                "--target",
                "x86_64-apple-darwin",
                "--target",
                "aarch64-apple-darwin",
            ],
            vec!["--min-macos", "15.0", "--min-macos", "15.0"],
        ] {
            assert!(
                package_options(&args.into_iter().map(str::to_owned).collect::<Vec<_>>()).is_err()
            );
        }
        for target in [
            "aarch64-apple-darwin",
            "x86_64-apple-darwin",
            "aarch64-unknown-linux-gnu",
            "x86_64-unknown-linux-gnu",
            "aarch64-pc-windows-msvc",
            "x86_64-pc-windows-msvc",
        ] {
            target_platform(target)?;
        }
        Ok(())
    }
    #[test]
    #[cfg(target_os = "macos")]
    fn prepares_both_macos_architectures_and_rejects_universal_binaries() -> Result<()> {
        let temp = tempfile::tempdir()?;
        let source = temp.path().join("main.c");
        fs::write(&source, "int main(void) { return 0; }\n")?;
        let mut binaries = Vec::new();
        for arch in ["arm64", "x86_64"] {
            let binary = temp.path().join(arch);
            super::super::run(
                Command::new("/usr/bin/clang")
                    .args([
                        "-arch",
                        arch,
                        "-mmacosx-version-min=15.0",
                        "-Wl,-rpath,/valle-test",
                    ])
                    .arg(&source)
                    .arg("-o")
                    .arg(&binary),
            )?;
            assert_eq!(inspect(&binary)?.arch, arch);
            prepare_executable(&binary)?;
            let info = inspect(&binary)?;
            assert_eq!(info.arch, arch);
            assert!(info.rpaths.is_empty());
            super::super::run(
                Command::new("/usr/bin/codesign")
                    .args(["--verify", "--strict"])
                    .arg(&binary),
            )?;
            binaries.push(binary);
        }
        let universal = temp.path().join("universal");
        super::super::run(
            Command::new("/usr/bin/lipo")
                .arg("-create")
                .args(&binaries)
                .arg("-output")
                .arg(&universal),
        )?;
        assert!(inspect(&universal).is_err());
        Ok(())
    }
    #[test]
    fn reads_weak_edges_paths_with_spaces_and_ignores_install_id() -> Result<()> {
        let object = parse_loads(
            "cmd LC_ID_DYLIB\nname @rpath/self.dylib (offset 24)\ncmd LC_LOAD_WEAK_DYLIB\nname /path with spaces/lib.dylib (offset 24)\ncmd LC_RPATH\npath @loader_path/../lib (offset 12)\ncmd LC_BUILD_VERSION\nminos 14.2\n",
        )?;
        assert_eq!(object.dependencies, ["/path with spaces/lib.dylib"]);
        assert_eq!(object.rpaths, ["@loader_path/../lib"]);
        assert_eq!(version(&object.minimum)?, [14, 2, 0]);
        Ok(())
    }
    #[test]
    fn validates_macos_versions() -> Result<()> {
        assert!(version("15.10")? > version("15.9")?);
        assert!(version("15.0.0.1").is_err());
        Ok(())
    }
}

#[cfg(test)]
mod contract_tests {
    use super::*;

    #[test]
    fn package_refuses_unowned_output_before_running_a_build() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("dist")).unwrap();
        fs::write(root.path().join("dist/user-file"), "keep").unwrap();
        for args in [vec![], vec!["--min-macos".to_owned(), "14.2".to_owned()]] {
            assert!(package(root.path(), &args).is_err());
            assert_eq!(
                fs::read_to_string(root.path().join("dist/user-file")).unwrap(),
                "keep"
            );
        }
        assert!(package(root.path(), &["--bad".to_owned()]).is_err());
        assert!(package(root.path(), &["--min-macos".to_owned(), "bad".to_owned()]).is_err());
        assert_eq!(display_version([14, 2, 0]), "14.2");
        assert_eq!(display_version([14, 2, 1]), "14.2.1");
        assert!(parse_loads("cmd LC_BUILD_VERSION\nminos invalid\n").is_err());
        assert!(capture(&mut Command::new("/nonexistent/valle-test-command")).is_err());
        assert!(capture(&mut Command::new("/usr/bin/false")).is_err());
    }

    #[test]
    #[cfg(target_os = "macos")]
    #[ignore = "requires the built distribution and real macOS signing tools"]
    fn copied_product_can_be_prepared_signed_and_inspected() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let temp = tempfile::tempdir().unwrap();
        let binary = temp.path().join("Valle with spaces");
        fs::copy(root.join("dist/bin/valle"), &binary).unwrap();
        prepare_executable(&binary).unwrap();
        let info = inspect(&binary).unwrap();
        assert!(info.rpaths.is_empty());
        assert!(info.dependencies.iter().all(|name| system_library(name)));
        assert!(version(&info.minimum).unwrap() > [0, 0, 0]);
        assert_eq!(hash_file(&binary).unwrap().len(), 64);
        assert!(
            capture(Command::new(binary).arg("--version"))
                .unwrap()
                .starts_with("valle ")
        );
    }
}
