name: Package Linux arm64

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ci:
        type: boolean
        default: false

permissions:
  contents: read

concurrency:
  group: package-linux-arm64-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  package:
    uses: ./.github/workflows/build-linux.yml
    with:
      ci: ${{ inputs.ci || false }}
      arch: arm64
      target: aarch64-unknown-linux-gnu
      machine: aarch64
